(() => {
const root=document.querySelector('.smart-library'); if(!root) return; const role=root.dataset.role; const manager=['admin','manager','employee'].includes(role);
const api={get:(a,p={})=>{const u=new URL('advanced_api.php',location.href);u.searchParams.set('action',a);Object.entries(p).forEach(([k,v])=>v!==''&&v!=null&&u.searchParams.set(k,v));return fetch(u,{cache:'no-store',credentials:'same-origin'}).then(r=>r.json()).then(x=>{if(!x.ok)throw new Error(x.message);return x.data})},post:(a,d={})=>fetch(`advanced_api.php?action=${encodeURIComponent(a)}`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(d)}).then(r=>r.json()).then(x=>{if(!x.ok)throw new Error(x.message);return x.data})};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])); const money=n=>Number(n||0).toLocaleString('vi-VN')+'đ'; const date=s=>s?new Date(s+'T00:00:00').toLocaleDateString('vi-VN'):'--';
function toast(m,err=false){let t=document.createElement('div');t.textContent=m;Object.assign(t.style,{position:'fixed',right:'18px',bottom:'82px',zIndex:9999,padding:'12px 16px',borderRadius:'12px',background:err?'#b42338':'#172033',color:'#fff',boxShadow:'0 10px 30px #0002'});document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
function updateTabIndicator(){const tabs=document.querySelector('#smartTabs'),active=tabs?.querySelector('button.active'),indicator=document.querySelector('#smartTabIndicator');if(!tabs||!active||!indicator)return;indicator.style.width=active.offsetWidth+'px';indicator.style.transform=`translateX(${active.offsetLeft}px)`;}
function setTabBadge(name,value){const badge=document.querySelector(`[data-tab-badge="${name}"]`);if(!badge)return;const n=Number(value||0);badge.hidden=n<=0;badge.textContent=n>99?'99+':String(n)}
function tab(name){document.querySelectorAll('#smartTabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.smart-panel').forEach(p=>{const active=p.dataset.panel===name;p.classList.toggle('active',active);if(active){p.classList.remove('panel-enter');void p.offsetWidth;p.classList.add('panel-enter')}});requestAnimationFrame(updateTabIndicator);load(name)}
document.querySelectorAll('#smartTabs button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
document.querySelector('#smartTabs')?.addEventListener('scroll',updateTabIndicator,{passive:true});window.addEventListener('resize',updateTabIndicator);
function genreTheme(name=''){const v=String(name||'').toLowerCase(),themes=[{k:['ngôn tình','tình'],c:['#ec4899','#8b5cf6'],i:'fa-heart'},{k:['công nghệ','kỹ thuật'],c:['#2563eb','#06b6d4'],i:'fa-microchip'},{k:['y học','sức khỏe'],c:['#0ea5e9','#14b8a6'],i:'fa-staff-snake'},{k:['phiêu lưu'],c:['#4f46e5','#0ea5e9'],i:'fa-compass'},{k:['khoa học'],c:['#2563eb','#7c3aed'],i:'fa-flask'},{k:['kinh dị','trinh thám'],c:['#312e81','#0891b2'],i:'fa-ghost'},{k:['nấu ăn'],c:['#f59e0b','#fb7185'],i:'fa-utensils'},{k:['thể thao'],c:['#16a34a','#0ea5e9'],i:'fa-person-running'},{k:['ngoại ngữ','giáo dục'],c:['#0f766e','#6366f1'],i:'fa-book-open-reader'},{k:['kinh tế','kỹ năng'],c:['#2563eb','#ec4899'],i:'fa-chart-line'}];return themes.find(t=>t.k.some(k=>v.includes(k)))||{c:['#2563eb','#4338ca'],i:'fa-book-open'}}
function smartCover(book){const raw=String(book?.HinhAnh||'').trim();if(raw)return raw;const theme=genreTheme(book?.TenTheLoai||book?.TenSach||''),title=String(book?.TenSach||'Sách').replace(/[&<>"']/g,'').slice(0,34),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="240" height="320"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${theme.c[0]}"/><stop offset="1" stop-color="${theme.c[1]}"/></linearGradient></defs><rect width="240" height="320" rx="26" fill="url(#g)"/><circle cx="190" cy="55" r="45" fill="rgba(255,255,255,.12)"/><text x="24" y="150" font-family="Arial" font-size="24" font-weight="700" fill="#fff">${title}</text><text x="24" y="278" font-family="Arial" font-size="14" fill="rgba(255,255,255,.8)">${String(book?.TacGia||'Thư viện').replace(/[&<>"']/g,'').slice(0,24)}</text></svg>`;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}
async function load(name){try{if(name==='overview')await overview();if(name==='copies')await copies();if(name==='discover')await discover();if(name==='queue')await queue();if(name==='notifications')await notifications();if(name==='fines')await fines();if(name==='inventory')await inventory();if(name==='staff')await staff();if(name==='audit')await audit();if(name==='card')await card();if(name==='profile')await profile();}catch(e){toast(e.message,true)}}
async function overview(){
  const [d,ops]=await Promise.all([api.get('overview'),manager?api.get('home_dashboard').catch(()=>null):Promise.resolve(null)]),s=d.summary||{};
  const metrics=[
    {key:'available',label:'Có sẵn',value:s.availableCopies||0,icon:'fa-book-open',tone:'blue',status:'Ổn định',note:'Cuốn sẵn sàng phục vụ'},
    {key:'borrowed',label:'Đang mượn',value:s.borrowedCopies||0,icon:'fa-arrow-right-arrow-left',tone:'cyan',status:+s.borrowedCopies?'Đang hoạt động':'Yên tĩnh',note:'Cuốn đang ở độc giả'},
    {key:'overdue',label:'Quá hạn',value:s.overdueLoans||0,icon:'fa-triangle-exclamation',tone:+s.overdueLoans?'red':'green',status:+s.overdueLoans?'Cần chú ý':'Ổn định',note:+s.overdueLoans?'Phiếu cần xử lý':'Không có phiếu quá hạn'},
    {key:'fine',label:'Phạt chưa thu',value:money(s.unpaidFines||0),icon:'fa-coins',tone:+s.unpaidFines?'amber':'green',status:+s.unpaidFines?'Theo dõi':'Ổn định',note:'Theo dữ liệu hiện tại'}
  ];
  document.querySelector('#smartMetrics').innerHTML=metrics.map((m,i)=>`<article class="smart-metric metric-${m.tone}" style="--delay:${i*70}ms"><div class="smart-metric-top"><span class="smart-metric-label">${esc(m.label)}</span><span class="smart-status-badge">${esc(m.status)}</span></div><strong class="smart-metric-value" data-smart-count="${typeof m.value==='number'?m.value:''}">${esc(m.value)}</strong><small>${esc(m.note)}</small><i class="fa-solid ${m.icon} smart-metric-watermark"></i><div class="smart-spark"><i></i><i></i><i></i><i></i><i></i><i></i></div></article>`).join('');
  document.querySelectorAll('[data-smart-count]').forEach(node=>{const target=Number(node.dataset.smartCount||0);let start=0,t0=performance.now();const tick=t=>{const p=Math.min(1,(t-t0)/650),v=Math.round(start+(target-start)*(1-Math.pow(1-p,3)));node.textContent=v.toLocaleString('vi-VN');if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});

  const maxBorrow=Math.max(1,...(d.top||[]).map(x=>Number(x.LuotMuon||0)));
  document.querySelector('#topBooks').innerHTML=(d.top||[]).map((x,i)=>`<button type="button" class="smart-rank-row" data-smart-book="${x.MaSach}"><span class="smart-rank-medal rank-${i+1}">${i<3?['🥇','🥈','🥉'][i]:'#'+(i+1)}</span><img src="${esc(smartCover(x))}" alt="${esc(x.TenSach)}"><span class="smart-rank-copy"><b>${esc(x.TenSach)}</b><small>${esc(x.TacGia||x.TenTheLoai||'Chưa rõ')}</small><span class="smart-progress"><i style="width:${Math.max(6,Number(x.LuotMuon||0)/maxBorrow*100)}%"></i></span></span><strong>${Number(x.LuotMuon||0)}<small> lượt</small></strong></button>`).join('')||'<p class="muted">Chưa có dữ liệu.</p>';
  document.querySelectorAll('[data-smart-book]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.smartBook;tab('discover');setTimeout(()=>{const input=document.querySelector('#detailBookId');if(input){input.value=id;document.querySelector('#loadBookDetail')?.click()}},80)});

  const maxCat=Math.max(1,...(d.cats||[]).map(x=>Number(x.LuotMuon||0)));
  document.querySelector('#topCategories').innerHTML=(d.cats||[]).map((x,i)=>{const theme=genreTheme(x.TenTheLoai);return `<div class="smart-category-row" style="--c1:${theme.c[0]};--c2:${theme.c[1]}"><span class="smart-category-icon"><i class="fa-solid ${theme.i}"></i></span><span class="smart-category-copy"><b>${esc(x.TenTheLoai)}</b><small>${Number(x.SoDauSach||0)} đầu sách • ${Number(x.TongSoLuong||0)} cuốn</small><span class="smart-progress"><i style="width:${Math.max(6,Number(x.LuotMuon||0)/maxCat*100)}%"></i></span></span><strong>${Number(x.LuotMuon||0)}<small> lượt</small></strong></div>`}).join('')||'<p class="muted">Chưa có dữ liệu.</p>';

  const alerts=[];
  if(+s.overdueLoans)alerts.push({icon:'fa-clock',title:`${s.overdueLoans} phiếu đang quá hạn`,level:'Khẩn',tone:'critical',action:'loan'});
  if(+s.unpaidFines)alerts.push({icon:'fa-coins',title:`${money(s.unpaidFines)} tiền phạt chưa thu`,level:'Quan trọng',tone:'important',action:'fines'});
  if(+s.zeroStock)alerts.push({icon:'fa-book',title:`${s.zeroStock} đầu sách đang hết tồn kho`,level:'Quan trọng',tone:'important',action:'inventory'});
  if(+s.waitingReservations)alerts.push({icon:'fa-bookmark',title:`${s.waitingReservations} lượt đang chờ sách`,level:'Theo dõi',tone:'watch',action:'queue'});
  if(+s.lockedAccounts)alerts.push({icon:'fa-lock',title:`${s.lockedAccounts} tài khoản đang khóa/ngừng hoạt động`,level:'Theo dõi',tone:'watch',action:'command'});
  if(+s.tomorrowUnderstaffed)alerts.push({icon:'fa-user-clock',title:`${s.tomorrowUnderstaffed} ca ngày mai chưa có người`,level:'Quan trọng',tone:'important',action:'staff'});
  if(!alerts.length)alerts.push({icon:'fa-circle-check',title:'Không có cảnh báo đáng chú ý',level:'Ổn định',tone:'ok',action:''});
  document.querySelector('#alertCenter').innerHTML=alerts.map((a,i)=>`<div class="smart-alert-row alert-${a.tone}" style="--delay:${i*60}ms"><span class="smart-alert-icon"><i class="fa-solid ${a.icon}"></i></span><span class="smart-alert-copy"><b>${esc(a.title)}</b><small>${esc(a.level)}</small></span>${a.action?`<button type="button" class="smart-alert-action" data-alert-action="${a.action}">Xem <i class="fa-solid fa-arrow-right"></i></button>`:''}</div>`).join('');
  document.querySelectorAll('[data-alert-action]').forEach(btn=>btn.onclick=()=>{const a=btn.dataset.alertAction;if(a==='fines'||a==='inventory'||a==='queue'||a==='staff')tab(a);else if(a==='loan'&&window.loadPage)loadPage('muontra.php','Mượn - Trả');else window.openLibraryCommand?.()});

  const totalCopies=Number(s.availableCopies||0)+Number(s.borrowedCopies||0)+Number(s.heldCopies||0),alertCount=Number(s.overdueLoans||0)+Number(s.waitingReservations||0)+Number(s.zeroStock||0)+Number(s.tomorrowUnderstaffed||0);
  const put=(id,value)=>{const n=document.querySelector(id);if(n)n.textContent=value};
  put('#radarStock',totalCopies?Math.round(Number(s.availableCopies||0)/totalCopies*100)+'%':'--');put('#radarLoan',Number(s.borrowedCopies||0));put('#radarAlert',alertCount);put('#radarAccount',Number(s.lockedAccounts||0)?`${s.lockedAccounts} khóa`:'Ổn');
  setTabBadge('queue',s.waitingReservations);setTabBadge('fines',Number(s.unpaidFines||0)>0?1:0);setTabBadge('inventory',s.zeroStock);setTabBadge('staff',s.tomorrowUnderstaffed);

  const sync=document.querySelector('#smartLastSync');if(sync)sync.innerHTML=`<i class="fa-regular fa-clock"></i> Cập nhật ${new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}`;
  const strip=document.querySelector('#smartAnalyticsStrip'),feed=document.querySelector('#smartActivityFeed');
  if(ops){const t=ops.today||{};strip.innerHTML=`<div class="smart-strip-track"><span><i class="fa-solid fa-arrow-up-right-from-square"></i><b>${Number(t.borrowedToday||0)}</b> Mượn hôm nay</span><span><i class="fa-solid fa-arrow-rotate-left"></i><b>${Number(t.returnedToday||0)}</b> Trả hôm nay</span><span><i class="fa-solid fa-triangle-exclamation"></i><b>${Number(t.newOverdueToday||0)}</b> Quá hạn mới</span><span><i class="fa-solid fa-box-open"></i><b>${Number(t.importedCopiesToday||0)}</b> Cuốn nhập hôm nay</span><span><i class="fa-solid fa-user-plus"></i><b>${Number(t.newReadersToday||0)}</b> Độc giả mới</span></div>`;const acts=ops.activity||[];feed.innerHTML=acts.length?acts.slice(0,8).map((x,i)=>`<div class="smart-feed-row" style="--delay:${i*55}ms"><span class="smart-feed-dot"></span><span><b>${esc(x.HanhDong||'Hoạt động')}</b><small>${esc(x.NguoiThucHien||'Hệ thống')} • ${new Date(x.NgayTao).toLocaleString('vi-VN')}${x.DoiTuong?' • '+esc(x.DoiTuong):''}</small></span></div>`).join(''):`<div class="smart-empty-state"><i class="fa-solid fa-clock-rotate-left"></i><span>Chưa có hoạt động mới được ghi nhận.</span></div>`}else{strip.innerHTML=`<div class="smart-strip-track"><span><i class="fa-solid fa-book-open"></i><b>${Number(s.availableCopies||0)}</b> Cuốn có sẵn</span><span><i class="fa-solid fa-arrow-right-arrow-left"></i><b>${Number(s.borrowedCopies||0)}</b> Đang mượn</span><span><i class="fa-solid fa-bookmark"></i><b>${Number(s.waitingReservations||0)}</b> Đang giữ chỗ</span></div>`;feed.innerHTML=`<div class="smart-empty-state"><i class="fa-solid fa-shield-halved"></i><span>Nhật ký vận hành chỉ hiển thị cho nhân viên được phân quyền.</span></div>`}
  requestAnimationFrame(updateTabIndicator);
}

let copyCache=[];async function copies(){copyCache=await api.get('copies');renderCopies(copyCache)} function renderCopies(rows){document.querySelector('#copyTable').innerHTML=rows.map(x=>`<tr><td><b>${esc(x.MaVach)}</b></td><td>${esc(x.TenSach)}</td><td>${esc(x.ViTri||'--')}</td><td><span class="pill ${x.TrangThai==='Có sẵn'?'good':x.TrangThai==='Đang mượn'?'warn':'bad'}">${esc(x.TrangThai)}</span></td><td><img class="qr-thumb" alt="QR" src="https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(x.MaVach)}"></td></tr>`).join('')}
document.querySelector('#copySearch')?.addEventListener('input',e=>{let q=e.target.value.toLowerCase();renderCopies(copyCache.filter(x=>(x.MaVach+' '+x.TenSach).toLowerCase().includes(q))) });
let borrowReader=null,borrowCodes=[],returnCodes=[]; async function lookup(code){return api.get('scan_lookup',{code})} function chips(id,arr){document.querySelector(id).innerHTML=arr.map(c=>`<span class="chip">${esc(c)} <button data-code="${esc(c)}">×</button></span>`).join('');document.querySelectorAll(id+' button').forEach(b=>b.onclick=()=>{let a=id==='#borrowCopies'?borrowCodes:returnCodes;a.splice(a.indexOf(b.dataset.code),1);chips(id,a)})}
async function addBorrow(){let el=document.querySelector('#borrowScan'),code=el.value.trim();if(!code)return;try{let r=await lookup(code);if(r.type==='reader'){borrowReader=r.item;document.querySelector('#borrowReader').innerHTML=`✅ <b>${esc(r.item.HoTen)}</b> • DG${String(r.item.MaDocGia).padStart(3,'0')}`;}else{if(r.item.TrangThai!=='Có sẵn')throw new Error(`Cuốn ${code} hiện ${r.item.TrangThai}`);if(!borrowCodes.includes(code))borrowCodes.push(code);chips('#borrowCopies',borrowCodes)}el.value=''}catch(e){toast(e.message,true)}} document.querySelector('#borrowAdd')?.addEventListener('click',addBorrow);document.querySelector('#borrowScan')?.addEventListener('keydown',e=>{if(e.key==='Enter')addBorrow()});
async function addReturn(){let el=document.querySelector('#returnScan'),code=el.value.trim();if(!code)return;try{let r=await lookup(code);if(r.type!=='copy')throw new Error('Đây không phải mã cuốn sách.');if(r.item.TrangThai!=='Đang mượn')throw new Error(`Cuốn ${code} không ở trạng thái đang mượn.`);if(!returnCodes.includes(code))returnCodes.push(code);chips('#returnCopies',returnCodes);el.value=''}catch(e){toast(e.message,true)}}document.querySelector('#returnAdd')?.addEventListener('click',addReturn);document.querySelector('#returnScan')?.addEventListener('keydown',e=>{if(e.key==='Enter')addReturn()});
document.querySelector('#confirmBorrow')?.addEventListener('click',async()=>{if(!borrowReader||!borrowCodes.length)return toast('Chọn độc giả và ít nhất 1 cuốn.',true);try{let d=await api.post('quick_borrow',{readerId:borrowReader.MaDocGia,codes:borrowCodes});toast(`Đã tạo phiếu #${d.loanId}, hạn ${date(d.dueDate)}`);borrowReader=null;borrowCodes=[];document.querySelector('#borrowReader').textContent='Chưa chọn độc giả';chips('#borrowCopies',borrowCodes);overview()}catch(e){toast(e.message,true)}});document.querySelector('#confirmReturn')?.addEventListener('click',async()=>{if(!returnCodes.length)return toast('Chưa có cuốn cần trả.',true);try{await api.post('quick_return',{codes:returnCodes});toast('Đã trả sách.');returnCodes=[];chips('#returnCopies',returnCodes);overview()}catch(e){toast(e.message,true)}});
document.querySelector('#cameraScan')?.addEventListener('click',async()=>{if(!('BarcodeDetector'in window))return toast('Trình duyệt này chưa hỗ trợ quét trực tiếp. Hãy nhập mã thủ công.',true);try{let video=document.querySelector('#scanVideo');video.hidden=false;let stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.srcObject=stream;await video.play();let detector=new BarcodeDetector({formats:['qr_code','code_128','ean_13']});let timer=setInterval(async()=>{let codes=await detector.detect(video).catch(()=>[]);if(codes[0]){clearInterval(timer);stream.getTracks().forEach(t=>t.stop());video.hidden=true;document.querySelector('#borrowScan').value=codes[0].rawValue;addBorrow()}},400)}catch(e){toast('Không mở được camera.',true)}});
async function discover(){if(role!=='customer'){document.querySelector('#recommendations').innerHTML='<p class="muted">Đăng nhập bằng tài khoản độc giả để nhận gợi ý cá nhân hóa.</p>';document.querySelector('#wishlist').innerHTML='<p class="muted">Danh sách muốn đọc dành cho độc giả.</p>';return}let [r,w]=await Promise.all([api.get('recommendations'),api.get('wishlist')]);const card=x=>`<div class="book-card"><img src="${esc(x.HinhAnh||'https://via.placeholder.com/90x120?text=Book')}" alt=""><div><h4>${esc(x.TenSach)}</h4><p>${esc(x.TacGia||'')}</p><p>${+x.SoLuong>0?'✅ Có sẵn':'⏳ Tạm hết'}</p><button class="smart-btn" data-fav="${x.MaSach}">♡ Muốn đọc</button></div></div>`;document.querySelector('#recommendations').innerHTML=r.map(card).join('')||'<p class="muted">Mượn thêm vài cuốn để hệ thống hiểu sở thích của bạn.</p>';document.querySelector('#wishlist').innerHTML=w.map(card).join('')||'<p class="muted">Chưa có sách yêu thích.</p>';document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=async()=>{await api.post('wishlist_toggle',{bookId:+b.dataset.fav});toast('Đã cập nhật danh sách muốn đọc.');discover()})}
document.querySelector('#loadBookDetail')?.addEventListener('click',async()=>{let id=+document.querySelector('#detailBookId').value;if(!id)return;try{let d=await api.get('book_detail',{id}),b=d.book;document.querySelector('#bookDetail').innerHTML=`<div class="list-row"><div><h3>${esc(b.TenSach)}</h3><p class="muted">${esc(b.TacGia||'')} • ${esc(b.TenTheLoai||'')}</p><p>${esc(b.MoTa||'Chưa có mô tả.')}</p><p><b>ISBN:</b> ${esc(b.ISBN||'--')} • <b>Vị trí:</b> ${esc(b.ViTriKe||'--')} • <b>Có sẵn:</b> ${b.SoLuong}</p><p><b>Đánh giá:</b> ${Number(b.DiemDanhGia||0).toFixed(1)}/5 (${b.SoDanhGia}) • <b>Lượt mượn:</b> ${b.LuotMuon}</p>${manager?`<div class="scan-row"><input id="bookIsbnEdit" value="${esc(b.ISBN||'')}" placeholder="ISBN"><input id="bookLocationEdit" value="${esc(b.ViTriKe||'')}" placeholder="Khu A – Kệ 03 – Tầng 2"><button class="smart-btn" id="bookMetaSave">Lưu ISBN/vị trí</button></div>`:''}</div></div>${(d.reviews||[]).map(r=>`<div class="list-row"><span>⭐ ${r.SoSao}/5 • ${esc(r.HoTen)}<br><small>${esc(r.NoiDung||'')}</small></span>${['admin','manager'].includes(role)?`<button class="smart-btn" data-hide-review="${r.MaDanhGia}">Ẩn</button>`:''}</div>`).join('')}`;if(manager&&document.querySelector('#bookMetaSave'))document.querySelector('#bookMetaSave').onclick=async()=>{try{await api.post('book_meta_update',{bookId:id,isbn:document.querySelector('#bookIsbnEdit').value,location:document.querySelector('#bookLocationEdit').value});toast('Đã lưu ISBN và vị trí kệ.');document.querySelector('#loadBookDetail').click()}catch(e){toast(e.message,true)}};document.querySelectorAll('[data-hide-review]').forEach(btn=>btn.onclick=async()=>{await api.post('review_moderate',{id:+btn.dataset.hideReview,status:'Ẩn'});toast('Đã ẩn đánh giá.');document.querySelector('#loadBookDetail').click()});if(role==='customer')document.querySelector('#bookDetail').insertAdjacentHTML('beforeend',`<div class="scan-row" style="margin-top:12px"><select id="reviewStars">${[5,4,3,2,1].map(n=>`<option value="${n}">${n} sao</option>`).join('')}</select><input id="reviewText" placeholder="Nhận xét của bạn"><button class="smart-btn" id="reviewSave">Gửi đánh giá</button><button class="smart-btn" id="queueJoin">Vào hàng chờ</button></div>`),document.querySelector('#reviewSave').onclick=async()=>{try{await api.post('review_save',{bookId:id,stars:+document.querySelector('#reviewStars').value,text:document.querySelector('#reviewText').value});toast('Đã lưu đánh giá.');document.querySelector('#loadBookDetail').click()}catch(e){toast(e.message,true)}},document.querySelector('#queueJoin').onclick=async()=>{try{let x=await api.post('queue_join',{bookId:id});toast(`Đã vào hàng chờ vị trí #${x.position}`);queue()}catch(e){toast(e.message,true)}}}catch(e){toast(e.message,true)}});
async function queue(){let rows=await api.get('queue');document.querySelector('#queueList').innerHTML=rows.map(x=>`<div class="list-row"><span><b>${esc(x.TenSach)}</b><br><small>${esc(x.HoTen)} • #${x.ThuTu||'-'} ${x.GiuDen?'• giữ đến '+new Date(x.GiuDen).toLocaleString('vi-VN'):''}</small></span><span class="pill ${x.TrangThai==='Đang giữ'?'good':'warn'}">${esc(x.TrangThai)}</span>${manager&&x.TrangThai==='Đang chờ'?`<button class="smart-btn" data-hold="${x.MaSach}">Giữ cho người đầu</button>`:''}</div>`).join('')||'<p class="muted">Chưa có hàng chờ.</p>';document.querySelectorAll('[data-hold]').forEach(b=>b.onclick=async()=>{try{await api.post('queue_hold_next',{bookId:+b.dataset.hold});toast('Đã giữ sách 24 giờ cho người đầu hàng chờ.');queue()}catch(e){toast(e.message,true)}})}
async function notifications(){let d=await api.get('notifications');document.querySelector('#notificationList').innerHTML=d.rows.map(x=>`<div class="list-row"><span><b>${esc(x.TieuDe)}</b><br><small>${esc(x.NoiDung)} • ${new Date(x.NgayTao).toLocaleString('vi-VN')}</small></span><button class="smart-btn" data-read="${x.MaThongBao}">${x.DaDoc==1?'Đã đọc':'Đánh dấu đọc'}</button></div>`).join('')||'<p class="muted">Không có thông báo.</p>';document.querySelectorAll('[data-read]').forEach(b=>b.onclick=async()=>{await api.post('notification_read',{id:+b.dataset.read});notifications();window.refreshLibraryNotifications?.()})}
async function fines(){let d=await api.get('fines'),t=d.totals||{};document.querySelector('#fineMetrics').innerHTML=[['Tổng phát sinh',money(t.Tong)],['Đã thu',money(t.DaThu)],['Chưa thu',money(t.ChuaThu)]].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');document.querySelector('#fineTable').innerHTML=d.rows.map(x=>`<tr><td>#${x.MaTienPhat}</td><td>${esc(x.HoTen)}</td><td>#${x.MaPhieuMuon}</td><td>${money(x.SoTien)}</td><td>${esc(x.TrangThai)}</td><td>${manager&&x.TrangThai==='Chưa thanh toán'?`<button class="smart-btn" data-paid="${x.MaTienPhat}">Đã thu</button> <button class="smart-btn" data-waive="${x.MaTienPhat}">Miễn</button>`:'--'}</td></tr>`).join('');document.querySelectorAll('[data-paid]').forEach(b=>b.onclick=async()=>{await api.post('fine_action',{id:+b.dataset.paid,mode:'paid'});fines()});document.querySelectorAll('[data-waive]').forEach(b=>b.onclick=async()=>{let reason=prompt('Lý do miễn/giảm:')||'';await api.post('fine_action',{id:+b.dataset.waive,mode:'waive',reason});fines()})}
document.querySelector('#loadReceipt')?.addEventListener('click',async()=>{let id=+document.querySelector('#receiptLoanId').value;if(!id)return;try{let r=await api.get('receipt',{loanId:id});document.querySelector('#receiptBox').innerHTML=`<div class="receipt" id="printReceipt"><h2>BIÊN NHẬN THƯ VIỆN</h2><div class="receipt-line"><span>Mã phiếu</span><b>#${r.MaPhieuMuon}</b></div><div class="receipt-line"><span>Độc giả</span><b>${esc(r.DocGia)}</b></div><div class="receipt-line"><span>Ngày mượn</span><b>${date(r.NgayMuon)}</b></div><div class="receipt-line"><span>Hạn trả</span><b>${date(r.HanTra)}</b></div><div class="receipt-line"><span>Sách</span><b>${esc((r.Sach||'').replaceAll('||',', '))}</b></div><div class="receipt-line"><span>Tiền phạt</span><b>${money(r.TienPhat)}</b></div></div><button class="smart-btn primary" id="printReceiptBtn">🖨️ In / Lưu PDF</button>`;document.querySelector('#printReceiptBtn').onclick=()=>{let html=document.querySelector('#printReceipt').outerHTML,w=open('','','width=800,height=700');w.document.write(`<html><head><title>Biên nhận #${id}</title><style>body{font-family:Arial;padding:40px}.receipt{max-width:650px;margin:auto}.receipt h2{text-align:center}.receipt-line{display:flex;justify-content:space-between;border-bottom:1px dotted #aaa;padding:10px}</style></head><body>${html}<script>print()<\/script></body></html>`);w.document.close()}}catch(e){toast(e.message,true)}});
async function inventory(){let d=await api.get('inventory');let sel=document.querySelector('#receiptSupplier');if(sel)sel.innerHTML='<option value="">Không chọn NCC</option>'+d.sup.map(x=>`<option value="${x.MaNCC}">${esc(x.TenNCC)}</option>`).join('');document.querySelector('#stockLogs').innerHTML=d.logs.map(x=>`<div class="list-row"><span><b>${esc(x.Loai)}</b> • ${esc(x.TenSach)}<br><small>${esc(x.GhiChu||'')} • ${new Date(x.NgayTao).toLocaleString('vi-VN')}</small></span><b>${x.SoLuong}</b></div>`).join('')||'<p class="muted">Chưa có nhật ký kho.</p>'}
document.querySelector('#receiptCreate')?.addEventListener('click',async()=>{try{let d=await api.post('receipt_create',{supplierId:+document.querySelector('#receiptSupplier').value||0,bookId:+document.querySelector('#receiptBookId').value,qty:+document.querySelector('#receiptQty').value,price:+document.querySelector('#receiptPrice').value,note:document.querySelector('#receiptNote').value});toast(`Đã tạo phiếu nhập #${d.receiptId} • ${money(d.total)}`);inventory();overview()}catch(e){toast(e.message,true)}});document.querySelector('#stockSave')?.addEventListener('click',async()=>{try{await api.post('stock_adjust',{bookId:+document.querySelector('#stockBookId').value,type:document.querySelector('#stockType').value,qty:+document.querySelector('#stockQty').value,note:document.querySelector('#stockNote').value});toast('Đã ghi nhận biến động kho.');inventory();overview()}catch(e){toast(e.message,true)}});document.querySelector('#supplierSave')?.addEventListener('click',async()=>{try{await api.post('supplier_save',{name:document.querySelector('#supplierName').value,phone:document.querySelector('#supplierPhone').value,email:document.querySelector('#supplierEmail').value,address:document.querySelector('#supplierAddress').value});toast('Đã thêm nhà cung cấp.');inventory()}catch(e){toast(e.message,true)}});
async function staff(){let [p,b]=await Promise.all([api.get('staff_profiles'),api.get('shift_board')]);document.querySelector('#staffProfiles').innerHTML=p.map(x=>`<div class="list-row"><span><b>${esc(x.HoTen)}</b><br><small>${esc(x.ChucVu||x.VaiTro||'Nhân viên')} • ${esc(x.TrangThai||'')} • ${x.SoCaThang} ca tháng này</small></span></div>`).join('');const mine=new Map((b.mine||[]).map(r=>[`${r.MaCa}|${r.NgayLam}`,r.TrangThai]));document.querySelector('#shiftBoard').innerHTML=b.rows.map(x=>{const status=mine.get(`${x.MaCa}|${x.NgayLam}`)||'';let action='';if(role==='employee'){if(status==='Chờ duyệt')action='<button class="smart-btn shift-registered" disabled>Đã đăng ký</button>';else if(status==='Đã duyệt')action='<button class="smart-btn shift-approved" disabled>Đã duyệt</button>';else action=`<button class="smart-btn" data-shift="${x.MaCa}" data-date="${x.NgayLam}">Đăng ký</button>`;}return `<div class="list-row"><span><b>${date(x.NgayLam)} • ${esc(x.TenCa)}</b><br><small>${String(x.GioBatDau).slice(0,5)}–${String(x.GioKetThuc).slice(0,5)} • ${x.DaPhanCong}/${x.SoNguoiToiDa||4} người</small></span>${action}</div>`}).join('');document.querySelectorAll('[data-shift]').forEach(b=>b.onclick=async()=>{try{b.disabled=true;await api.post('shift_register',{shiftId:+b.dataset.shift,date:b.dataset.date});staff()}catch(e){b.disabled=false;toast(e.message,true)}});if(['admin','manager'].includes(role)){let r=await api.get('shift_requests');document.querySelector('#shiftRequests').innerHTML=r.map(x=>`<div class="list-row"><span><b>${esc(x.HoTen)}</b> • ${date(x.NgayLam)} • ${esc(x.TenCa)}<br><small>${esc(x.TrangThai)}</small></span>${x.TrangThai==='Chờ duyệt'?`<span><button class="smart-btn" data-approve="${x.MaDangKy}">Duyệt</button> <button class="smart-btn" data-reject="${x.MaDangKy}">Từ chối</button></span>`:''}</div>`).join('');document.querySelectorAll('[data-approve],[data-reject]').forEach(b=>b.onclick=async()=>{await api.post('shift_decide',{id:+(b.dataset.approve||b.dataset.reject),mode:b.dataset.approve?'approve':'reject'});staff()})}}
let auditCache=[];async function audit(){auditCache=await api.get('audit');renderAudit(auditCache)}function renderAudit(r){document.querySelector('#auditList').innerHTML=r.map(x=>`<div class="timeline-item"><b>${esc(x.HanhDong)}</b> ${esc(x.DoiTuong||'')}<br><small>${esc(x.NguoiThucHien||'Hệ thống')} • ${new Date(x.NgayTao).toLocaleString('vi-VN')} ${x.ChiTiet?'• '+esc(x.ChiTiet):''}</small></div>`).join('')||'<p class="muted">Chưa có hoạt động mới.</p>'}document.querySelector('#auditSearch')?.addEventListener('input',e=>{let q=e.target.value.toLowerCase();renderAudit(auditCache.filter(x=>(x.NguoiThucHien+' '+x.HanhDong+' '+x.DoiTuong+' '+x.ChiTiet).toLowerCase().includes(q))) });
async function card(){let r=await api.get('reader_card'),code='DG'+String(r.MaDocGia).padStart(3,'0');document.querySelector('#libraryCard').innerHTML=`<div class="library-card" id="cardCapture"><div><small>THẺ THƯ VIỆN ĐIỆN TỬ</small><h2>${esc(r.HoTen)}</h2><p><b>${code}</b></p><p>${esc(r.Email||'')}<br>${esc(r.SDT||'')}</p><p>Ngày đăng ký: ${date(r.NgayDangKy)}<br>Hết hạn: ${date(r.NgayHetHanThe)}</p><span class="pill good">${esc(r.TrangThai||'Đang hoạt động')}</span></div><div class="qr"><img alt="QR độc giả" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(code)}"></div></div><button class="smart-btn primary" id="printCard">🖨️ In / Lưu thẻ PDF</button>`;document.querySelector('#printCard').onclick=()=>print()}
async function profile(){let d=await api.get('reading_profile'),s=d.summary||{};document.querySelector('#readingMetrics').innerHTML=[['📚 Cuốn đã đọc năm nay',s.SoCuonNam||0],['🧾 Lượt mượn năm nay',s.LuotMuonNam||0],['⏰ Trả đúng hạn',(s.TyLeDungHan??0)+'%'],['❤️ Thể loại yêu thích',d.favorite?.TenTheLoai||'--'],['🏆 Tháng đọc nhiều',d.bestMonth?.Thang||'--']].map(x=>`<div class="metric"><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join('');document.querySelector('#badgeList').innerHTML=(d.badges||[]).map(x=>`<span class="achievement">${esc(x)}</span>`).join('')||'<p class="muted">Tiếp tục đọc để mở huy hiệu.</p>'}
document.querySelector('#refreshSmart')?.addEventListener('click',()=>load(document.querySelector('#smartTabs .active')?.dataset.tab||'overview'));document.querySelector('#openCommand')?.addEventListener('click',()=>window.openLibraryCommand?.());
load('overview'); requestAnimationFrame(updateTabIndicator); window.refreshLibraryNotifications?.();
})();
