<?php
session_start();
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
require_once __DIR__.'/database/connect.php';
require_once __DIR__.'/auth.php';

function aok($data=null,$message=''){echo json_encode(['ok'=>true,'data'=>$data,'message'=>$message],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function afail($m,$s=400){http_response_code($s);echo json_encode(['ok'=>false,'message'=>$m],JSON_UNESCAPED_UNICODE);exit;}
function adata(){ $raw=file_get_contents('php://input'); $j=json_decode($raw?:'{}',true); return is_array($j)?$j:$_POST; }
function aall(mysqli_result $r){return $r->fetch_all(MYSQLI_ASSOC);} 
function managerLike(){return in_array(currentLibraryRoleKey(),['admin','manager','employee'],true);} 
function audit(mysqli $c,string $action,string $object='',string $detail=''):void{
 $uid=(int)($_SESSION['user_id']??0);$name=(string)($_SESSION['display_name']??$_SESSION['username']??'');$role=currentLibraryRoleKey();$ip=$_SERVER['REMOTE_ADDR']??'';
 $s=$c->prepare("INSERT INTO nhatkyhoatdong(MaTaiKhoan,NguoiThucHien,VaiTro,HanhDong,DoiTuong,ChiTiet,DiaChiIP) VALUES(NULLIF(?,0),?,?,?,?,?,?)");
 $s->bind_param('issssss',$uid,$name,$role,$action,$object,$detail,$ip);$s->execute();
}
function currentReaderId():int{return (int)($_SESSION['reader_id']??0);} function currentEmployeeId():int{return (int)($_SESSION['employee_id']??0);} 
if(empty($_SESSION['user_id'])) afail('Vui lòng đăng nhập.',401);
if(!syncLibrarySessionAccount($conn)) afail('Phiên đăng nhập không hợp lệ.',401);
$action=$_GET['action']??'';$d=adata();

switch($action){
case 'overview':
 $summary=$conn->query("SELECT
 (SELECT COUNT(*) FROM cuonsach WHERE TrangThai='Có sẵn') availableCopies,
 (SELECT COUNT(*) FROM cuonsach WHERE TrangThai='Đang mượn') borrowedCopies,
 (SELECT COUNT(*) FROM cuonsach WHERE TrangThai='Đang giữ chỗ') heldCopies,
 (SELECT COUNT(*) FROM phieumuon WHERE NgayTra IS NULL AND HanTra<CURDATE() AND COALESCE(TrangThai,'') NOT IN('Đã trả','Đã hủy','Hủy')) overdueLoans,
 (SELECT COUNT(*) FROM hangchodatsach WHERE TrangThai='Đang chờ') waitingReservations,
 (SELECT COALESCE(SUM(SoTien),0) FROM tienphat WHERE TrangThai='Chưa thanh toán') unpaidFines,
 (SELECT COUNT(*) FROM taikhoan WHERE COALESCE(TrangThai,'') IN('Khóa','Đã khóa','Ngừng hoạt động')) lockedAccounts,
 (SELECT COUNT(*) FROM sach WHERE SoLuong<=0) zeroStock,
 (SELECT COUNT(*) FROM calamviec c WHERE c.TrangThai='Hoạt động' AND (SELECT COUNT(*) FROM phancongca pc WHERE pc.MaCa=c.MaCa AND pc.NgayLam=DATE_ADD(CURDATE(),INTERVAL 1 DAY)) < LEAST(1,c.SoNguoiToiDa)) tomorrowUnderstaffed")->fetch_assoc();
 $top=aall($conn->query("SELECT s.MaSach,s.TenSach,s.TacGia,s.HinhAnh,COALESCE(t.TenTheLoai,'Chưa phân loại') TenTheLoai,COALESCE(SUM(ct.SoLuong),0) LuotMuon FROM sach s LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai LEFT JOIN chitietphieumuon ct ON ct.MaSach=s.MaSach GROUP BY s.MaSach,s.TenSach,s.TacGia,s.HinhAnh,t.TenTheLoai ORDER BY LuotMuon DESC,s.MaSach DESC LIMIT 5"));
 $cats=aall($conn->query("SELECT COALESCE(t.TenTheLoai,'Chưa phân loại') TenTheLoai,COUNT(DISTINCT s.MaSach) SoDauSach,COALESCE(SUM(s.SoLuong),0) TongSoLuong,COALESCE(SUM(ct.SoLuong),0) LuotMuon FROM sach s LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai LEFT JOIN chitietphieumuon ct ON ct.MaSach=s.MaSach GROUP BY t.MaTheLoai,t.TenTheLoai ORDER BY LuotMuon DESC,TongSoLuong DESC LIMIT 6"));
 $trend=aall($conn->query("SELECT DATE(NgayMuon) Ngay,COUNT(*) Luot FROM phieumuon WHERE NgayMuon>=DATE_SUB(CURDATE(),INTERVAL 29 DAY) GROUP BY DATE(NgayMuon) ORDER BY Ngay"));
 aok(compact('summary','top','cats','trend'));

case 'home_dashboard':
 if(!managerLike()) afail('Bạn không có quyền xem dashboard vận hành.',403);
 $days=[];
 for($i=6;$i>=0;$i--){
   $date=date('Y-m-d',strtotime("-$i day"));
   $label=date('d/m',strtotime($date));
   $safe=$conn->real_escape_string($date);
   $borrow=(int)$conn->query("SELECT COUNT(*) c FROM phieumuon WHERE DATE(NgayMuon)='$safe'")->fetch_assoc()['c'];
   $returned=(int)$conn->query("SELECT COUNT(*) c FROM phieumuon WHERE DATE(NgayTra)='$safe'")->fetch_assoc()['c'];
   $overdue=(int)$conn->query("SELECT COUNT(*) c FROM phieumuon WHERE DATE(HanTra)='$safe' AND (NgayTra IS NULL OR DATE(NgayTra)>HanTra) AND COALESCE(TrangThai,'') NOT IN('Đã hủy','Hủy')")->fetch_assoc()['c'];
   $days[]=['date'=>$date,'label'=>$label,'borrow'=>$borrow,'returned'=>$returned,'overdue'=>$overdue];
 }
 $today=$conn->query("SELECT
   (SELECT COUNT(*) FROM phieumuon WHERE DATE(NgayMuon)=CURDATE()) borrowedToday,
   (SELECT COUNT(*) FROM phieumuon WHERE DATE(NgayTra)=CURDATE()) returnedToday,
   (SELECT COUNT(*) FROM phieumuon WHERE NgayTra IS NULL AND HanTra<CURDATE() AND COALESCE(TrangThai,'') NOT IN('Đã trả','Đã hủy','Hủy')) overdueNow,
   (SELECT COUNT(*) FROM sach WHERE SoLuong<=0) zeroStock,
   (SELECT COUNT(*) FROM hangchodatsach WHERE TrangThai='Đang chờ') waitingReservations,
   (SELECT COUNT(*) FROM docgia WHERE NgayDangKy=CURDATE()) newReadersToday,
   (SELECT COUNT(*) FROM cuonsach WHERE NgayNhap=CURDATE()) importedCopiesToday,
   (SELECT COUNT(*) FROM phieumuon WHERE NgayTra IS NULL AND HanTra=DATE_SUB(CURDATE(),INTERVAL 1 DAY) AND COALESCE(TrangThai,'') NOT IN('Đã trả','Đã hủy','Hủy')) newOverdueToday")->fetch_assoc();
 $activity=[];
 $check=$conn->query("SHOW TABLES LIKE 'nhatkyhoatdong'");
 if($check && $check->num_rows){
   $activity=aall($conn->query("SELECT MaNhatKy,NguoiThucHien,VaiTro,HanhDong,DoiTuong,ChiTiet,NgayTao FROM nhatkyhoatdong ORDER BY MaNhatKy DESC LIMIT 12"));
 }
 aok(['days'=>$days,'today'=>$today,'activity'=>$activity,'system'=>['database'=>'Đã kết nối','php'=>PHP_VERSION,'serverTime'=>date('d/m/Y H:i:s')]]);

case 'copies':
 if(!managerLike()) afail('Bạn không có quyền xem quản lý từng cuốn.',403);
 $rows=aall($conn->query("SELECT c.*,s.TenSach,s.ISBN,COALESCE(c.ViTriKe,s.ViTriKe) ViTri FROM cuonsach c JOIN sach s ON s.MaSach=c.MaSach ORDER BY c.MaSach,c.MaCuon"));
 aok($rows);

case 'copy_update':
 if(!managerLike()) afail('Bạn không có quyền cập nhật cuốn sách.',403);
 $id=(int)($d['id']??0);$status=trim((string)($d['status']??''));$loc=trim((string)($d['location']??''));$note=trim((string)($d['note']??''));
 if(!$id||!in_array($status,['Có sẵn','Đang mượn','Đang giữ chỗ','Hỏng','Mất','Thanh lý'],true)) afail('Dữ liệu cuốn sách không hợp lệ.');
 $s=$conn->prepare("UPDATE cuonsach SET TrangThai=?,ViTriKe=NULLIF(?,''),GhiChu=NULLIF(?,'') WHERE MaCuon=?");$s->bind_param('sssi',$status,$loc,$note,$id);$s->execute(); audit($conn,'Cập nhật cuốn sách','#'.$id,$status);aok(null,'Đã cập nhật cuốn sách.');

case 'reader_card':
 $rid=currentReaderId(); if(managerLike() && !empty($_GET['readerId'])) $rid=(int)$_GET['readerId']; if(!$rid) afail('Tài khoản chưa liên kết độc giả.');
 $s=$conn->prepare("SELECT d.*,COUNT(DISTINCT pm.MaPhieuMuon) TongLuotMuon FROM docgia d LEFT JOIN phieumuon pm ON pm.MaDocGia=d.MaDocGia WHERE d.MaDocGia=? GROUP BY d.MaDocGia");$s->bind_param('i',$rid);$s->execute();$r=$s->get_result()->fetch_assoc(); if(!$r) afail('Không tìm thấy độc giả.',404);aok($r);

case 'scan_lookup':
 $code=trim((string)($_GET['code']??'')); if($code==='') afail('Chưa có mã cần quét.');
 if(preg_match('/^DG(\d+)$/i',$code,$m)){$id=(int)$m[1];$s=$conn->prepare("SELECT MaDocGia,HoTen,TrangThai,Email,SDT FROM docgia WHERE MaDocGia=?");$s->bind_param('i',$id);$s->execute();aok(['type'=>'reader','item'=>$s->get_result()->fetch_assoc()]);}
 $s=$conn->prepare("SELECT c.MaCuon,c.MaVach,c.TrangThai,c.MaSach,s.TenSach,s.SoLuong FROM cuonsach c JOIN sach s ON s.MaSach=c.MaSach WHERE c.MaVach=? LIMIT 1");$s->bind_param('s',$code);$s->execute();$r=$s->get_result()->fetch_assoc(); if(!$r) afail('Không tìm thấy mã độc giả/cuốn sách.',404);aok(['type'=>'copy','item'=>$r]);

case 'quick_borrow':
 if(!managerLike()) afail('Bạn không có quyền tạo phiếu mượn nhanh.',403);
 $rid=(int)($d['readerId']??0);$codes=array_values(array_unique(array_filter($d['codes']??[]))); if(!$rid||!$codes) afail('Cần chọn độc giả và ít nhất 1 cuốn sách.');
 $cfg=$conn->query("SELECT COALESCE(SoNgayMuon,14) SoNgayMuon FROM caidat ORDER BY MaCaiDat LIMIT 1")->fetch_assoc();$days=max(1,(int)($cfg['SoNgayMuon']??14));$emp=currentEmployeeId();$today=date('Y-m-d');$due=date('Y-m-d',strtotime("+$days days"));
 $conn->begin_transaction();try{
   $st=$conn->prepare("INSERT INTO phieumuon(MaDocGia,MaNhanVien,NgayMuon,HanTra,NgayTra,TrangThai) VALUES(?,?,?,?,NULL,'Đang mượn')");$empNull=$emp?:null;$st->bind_param('iiss',$rid,$empNull,$today,$due);$st->execute();$loan=$conn->insert_id;
   $bookGroups=[];$copyRows=[];$find=$conn->prepare("SELECT MaCuon,MaSach,TrangThai FROM cuonsach WHERE MaVach=? FOR UPDATE");
   foreach($codes as $code){$find->bind_param('s',$code);$find->execute();$row=$find->get_result()->fetch_assoc();if(!$row||$row['TrangThai']!=='Có sẵn') throw new Exception("Cuốn $code không còn sẵn.");$bookGroups[(int)$row['MaSach']][]=$row;}
   foreach($bookGroups as $bookId=>$copies){$qty=count($copies);$chk=$conn->prepare("SELECT SoLuong FROM sach WHERE MaSach=? FOR UPDATE");$chk->bind_param('i',$bookId);$chk->execute();$available=(int)$chk->get_result()->fetch_assoc()['SoLuong'];if($available<$qty) throw new Exception('Số lượng sách khả dụng không đủ.');$ct=$conn->prepare("INSERT INTO chitietphieumuon(MaPhieuMuon,MaSach,SoLuong,TienPhat) VALUES(?,?,?,0)");$ct->bind_param('iii',$loan,$bookId,$qty);$ct->execute();$ctid=$conn->insert_id;$u=$conn->prepare("UPDATE sach SET SoLuong=SoLuong-? WHERE MaSach=?");$u->bind_param('ii',$qty,$bookId);$u->execute();foreach($copies as $cr){$cid=(int)$cr['MaCuon'];$conn->query("UPDATE cuonsach SET TrangThai='Đang mượn' WHERE MaCuon=$cid");$lk=$conn->prepare("INSERT INTO chitietcuonmuon(MaCTPM,MaCuon) VALUES(?,?)");$lk->bind_param('ii',$ctid,$cid);$lk->execute();}}
   $conn->commit();audit($conn,'Mượn nhanh','Phiếu #'.$loan,implode(', ',$codes));aok(['loanId'=>$loan,'dueDate'=>$due],'Đã tạo phiếu mượn nhanh.');
 }catch(Throwable $e){$conn->rollback();afail($e->getMessage());}

case 'quick_return':
 if(!managerLike()) afail('Bạn không có quyền trả sách nhanh.',403);$codes=array_values(array_unique(array_filter($d['codes']??[])));if(!$codes) afail('Chưa có mã cuốn sách.');
 $done=[];$conn->begin_transaction();try{foreach($codes as $code){$s=$conn->prepare("SELECT c.MaCuon,c.MaSach,l.MaCTPM,ct.MaPhieuMuon FROM cuonsach c JOIN chitietcuonmuon l ON l.MaCuon=c.MaCuon JOIN chitietphieumuon ct ON ct.MaCTPM=l.MaCTPM JOIN phieumuon pm ON pm.MaPhieuMuon=ct.MaPhieuMuon WHERE c.MaVach=? AND c.TrangThai='Đang mượn' AND pm.NgayTra IS NULL ORDER BY pm.MaPhieuMuon DESC LIMIT 1");$s->bind_param('s',$code);$s->execute();$r=$s->get_result()->fetch_assoc();if(!$r) throw new Exception("Không tìm thấy lượt mượn đang mở cho $code.");$cid=(int)$r['MaCuon'];$bid=(int)$r['MaSach'];$loan=(int)$r['MaPhieuMuon'];$conn->query("UPDATE cuonsach SET TrangThai='Có sẵn' WHERE MaCuon=$cid");$conn->query("UPDATE sach SET SoLuong=SoLuong+1 WHERE MaSach=$bid");$remaining=$conn->query("SELECT COUNT(*) c FROM chitietcuonmuon l JOIN chitietphieumuon ct ON ct.MaCTPM=l.MaCTPM JOIN cuonsach c ON c.MaCuon=l.MaCuon WHERE ct.MaPhieuMuon=$loan AND c.TrangThai='Đang mượn'")->fetch_assoc()['c'];if((int)$remaining===0)$conn->query("UPDATE phieumuon SET NgayTra=CURDATE(),TrangThai='Đã trả' WHERE MaPhieuMuon=$loan");$done[]=$code;}
 $conn->commit();audit($conn,'Trả nhanh','Cuốn sách',implode(', ',$done));aok(['returned'=>$done],'Đã ghi nhận trả sách.');}catch(Throwable $e){$conn->rollback();afail($e->getMessage());}

case 'notifications':
 $uid=(int)$_SESSION['user_id'];$rid=currentReaderId();$eid=currentEmployeeId();
 if($rid){$q=$conn->prepare("SELECT pm.MaPhieuMuon,pm.HanTra,DATEDIFF(pm.HanTra,CURDATE()) conlai FROM phieumuon pm WHERE pm.MaDocGia=? AND pm.NgayTra IS NULL AND COALESCE(pm.TrangThai,'') NOT IN('Đã trả','Đã hủy','Hủy') AND pm.HanTra<=DATE_ADD(CURDATE(),INTERVAL 2 DAY)");$q->bind_param('i',$rid);$q->execute();foreach(aall($q->get_result()) as $x){$title=((int)$x['conlai']<0)?'Sách đang quá hạn':'Sắp đến hạn trả';$content=((int)$x['conlai']<0)?'Phiếu #'.$x['MaPhieuMuon'].' đã quá hạn '.abs((int)$x['conlai']).' ngày.':'Phiếu #'.$x['MaPhieuMuon'].' còn '.max(0,(int)$x['conlai']).' ngày đến hạn.';$chk=$conn->prepare("SELECT 1 FROM thongbao WHERE MaTaiKhoan=? AND TieuDe=? AND NoiDung=? LIMIT 1");$chk->bind_param('iss',$uid,$title,$content);$chk->execute();if(!$chk->get_result()->fetch_assoc()){$in=$conn->prepare("INSERT INTO thongbao(MaTaiKhoan,MaDocGia,TieuDe,NoiDung,Loai,DuongDan) VALUES(?,?,?,?,'warning','muontra.php')");$in->bind_param('iiss',$uid,$rid,$title,$content);$in->execute();}}}
 if($rid){$w=$conn->prepare("SELECT s.MaSach,s.TenSach FROM yeuthich y JOIN sach s ON s.MaSach=y.MaSach WHERE y.MaDocGia=? AND s.SoLuong>0");$w->bind_param('i',$rid);$w->execute();foreach(aall($w->get_result()) as $x){$title='Sách bạn quan tâm đã có sẵn';$content=$x['TenSach'].' hiện có thể mượn.';$chk=$conn->prepare("SELECT 1 FROM thongbao WHERE MaTaiKhoan=? AND TieuDe=? AND NoiDung=? AND NgayTao>=DATE_SUB(NOW(),INTERVAL 7 DAY) LIMIT 1");$chk->bind_param('iss',$uid,$title,$content);$chk->execute();if(!$chk->get_result()->fetch_assoc()){$in=$conn->prepare("INSERT INTO thongbao(MaTaiKhoan,MaDocGia,TieuDe,NoiDung,Loai,DuongDan) VALUES(?,?,?,?,'success','sach.php')");$in->bind_param('iiss',$uid,$rid,$title,$content);$in->execute();}}}
 if($rid){$r=$conn->prepare("SELECT MaYeuCau,MaPhieuMuon,TrangThai,HanTraMoi,LyDoTuChoi,NgayXuLy FROM yeucaugiahan WHERE MaDocGia=? AND TrangThai<>'Chờ duyệt' AND NgayXuLy IS NOT NULL AND NgayXuLy>=DATE_SUB(NOW(),INTERVAL 30 DAY) ORDER BY NgayXuLy DESC LIMIT 10");$r->bind_param('i',$rid);$r->execute();foreach(aall($r->get_result()) as $x){$approved=$x['TrangThai']==='Đã duyệt';$title=$approved?'Yêu cầu gia hạn đã được duyệt':'Yêu cầu gia hạn đã được xử lý';$content=$approved?'Phiếu #'.$x['MaPhieuMuon'].' được gia hạn đến '.date('d/m/Y',strtotime($x['HanTraMoi'])).'.':'Phiếu #'.$x['MaPhieuMuon'].' có trạng thái '.$x['TrangThai'].(!empty($x['LyDoTuChoi'])?' • '.$x['LyDoTuChoi']:'');$chk=$conn->prepare("SELECT 1 FROM thongbao WHERE MaTaiKhoan=? AND TieuDe=? AND NoiDung=? LIMIT 1");$chk->bind_param('iss',$uid,$title,$content);$chk->execute();if(!$chk->get_result()->fetch_assoc()){$type=$approved?'success':'warning';$in=$conn->prepare("INSERT INTO thongbao(MaTaiKhoan,MaDocGia,TieuDe,NoiDung,Loai,DuongDan) VALUES(?,?,?,?,?,'muontra.php')");$in->bind_param('iisss',$uid,$rid,$title,$content,$type);$in->execute();}}}
 if($rid){$r=$conn->prepare("SELECT dl.MaDatLich,dl.TrangThai,dl.NgayXuLy,s.TenSach,s.SoLuong FROM datlichmuon dl JOIN sach s ON s.MaSach=dl.MaSach WHERE dl.MaDocGia=? AND dl.TrangThai<>'Chờ xác nhận' AND COALESCE(dl.NgayXuLy,dl.NgayDat)>=DATE_SUB(NOW(),INTERVAL 30 DAY) ORDER BY COALESCE(dl.NgayXuLy,dl.NgayDat) DESC LIMIT 10");$r->bind_param('i',$rid);$r->execute();foreach(aall($r->get_result()) as $x){$title='Cập nhật đặt trước sách';$content=$x['TenSach'].' • '.$x['TrangThai'].((int)$x['SoLuong']>0?' • Hiện đang có sách':'');$chk=$conn->prepare("SELECT 1 FROM thongbao WHERE MaTaiKhoan=? AND TieuDe=? AND NoiDung=? LIMIT 1");$chk->bind_param('iss',$uid,$title,$content);$chk->execute();if(!$chk->get_result()->fetch_assoc()){$type=(int)$x['SoLuong']>0?'success':'info';$in=$conn->prepare("INSERT INTO thongbao(MaTaiKhoan,MaDocGia,TieuDe,NoiDung,Loai,DuongDan) VALUES(?,?,?,?,?,'muontra.php')");$in->bind_param('iisss',$uid,$rid,$title,$content,$type);$in->execute();}}}
 if($rid){$r=$conn->prepare("SELECT t.TenTheLoai,COUNT(*) c FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon JOIN sach s ON s.MaSach=ct.MaSach JOIN theloai t ON t.MaTheLoai=s.MaTheLoai WHERE pm.MaDocGia=? GROUP BY t.MaTheLoai,t.TenTheLoai ORDER BY SUM(ct.SoLuong) DESC LIMIT 1");$r->bind_param('i',$rid);$r->execute();if($x=$r->get_result()->fetch_assoc()){$title='Gợi ý mới dành cho bạn';$content='Có thêm gợi ý dựa trên thể loại '.$x['TenTheLoai'].' bạn thường đọc.';$chk=$conn->prepare("SELECT 1 FROM thongbao WHERE MaTaiKhoan=? AND TieuDe=? AND NgayTao>=DATE_SUB(NOW(),INTERVAL 14 DAY) LIMIT 1");$chk->bind_param('is',$uid,$title);$chk->execute();if(!$chk->get_result()->fetch_assoc()){$in=$conn->prepare("INSERT INTO thongbao(MaTaiKhoan,MaDocGia,TieuDe,NoiDung,Loai,DuongDan) VALUES(?,?,?,?,'info','trangchu.php')");$in->bind_param('iiss',$uid,$rid,$title,$content);$in->execute();}}}
 if($eid){$s=$conn->prepare("SELECT pc.NgayLam,c.TenCa,c.GioBatDau FROM phancongca pc JOIN calamviec c ON c.MaCa=pc.MaCa WHERE pc.MaNhanVien=? AND pc.NgayLam=DATE_ADD(CURDATE(),INTERVAL 1 DAY)");$s->bind_param('i',$eid);$s->execute();foreach(aall($s->get_result()) as $x){$title='Ca làm ngày mai';$content=$x['TenCa'].' lúc '.substr($x['GioBatDau'],0,5);$chk=$conn->prepare("SELECT 1 FROM thongbao WHERE MaTaiKhoan=? AND TieuDe=? AND NoiDung=? LIMIT 1");$chk->bind_param('iss',$uid,$title,$content);$chk->execute();if(!$chk->get_result()->fetch_assoc()){$in=$conn->prepare("INSERT INTO thongbao(MaTaiKhoan,MaNhanVien,TieuDe,NoiDung,Loai,DuongDan) VALUES(?,?,?,?,'info','calamviec.php')");$in->bind_param('iiss',$uid,$eid,$title,$content);$in->execute();}}}
 $s=$conn->prepare("SELECT * FROM thongbao WHERE MaTaiKhoan=? ORDER BY DaDoc ASC,NgayTao DESC LIMIT 30");$s->bind_param('i',$uid);$s->execute();$rows=aall($s->get_result());$unread=0;foreach($rows as $r)if(!(int)$r['DaDoc'])$unread++;aok(['rows'=>$rows,'unread'=>$unread]);
case 'notification_read': $id=(int)($d['id']??0);$uid=(int)$_SESSION['user_id'];$s=$conn->prepare("UPDATE thongbao SET DaDoc=1 WHERE MaThongBao=? AND MaTaiKhoan=?");$s->bind_param('ii',$id,$uid);$s->execute();aok();
case 'notification_read_all': $uid=(int)$_SESSION['user_id'];$s=$conn->prepare("UPDATE thongbao SET DaDoc=1 WHERE MaTaiKhoan=?");$s->bind_param('i',$uid);$s->execute();aok(['updated'=>$s->affected_rows],'Đã đánh dấu tất cả thông báo là đã đọc.');

case 'fines':
 if(!managerLike() && currentLibraryRoleKey()!=='customer') afail('Không có quyền.',403);$rid=currentReaderId();
 $where=$rid&&!managerLike()?" WHERE tp.MaDocGia=$rid ":'';$rows=aall($conn->query("SELECT tp.*,dg.HoTen,nv.HoTen NguoiThu FROM tienphat tp JOIN docgia dg ON dg.MaDocGia=tp.MaDocGia LEFT JOIN nhanvien nv ON nv.MaNhanVien=tp.MaNhanVienThu $where ORDER BY tp.MaTienPhat DESC"));$tot=$conn->query("SELECT COALESCE(SUM(SoTien),0) Tong,COALESCE(SUM(CASE WHEN TrangThai='Đã thanh toán' THEN SoTien ELSE 0 END),0) DaThu,COALESCE(SUM(CASE WHEN TrangThai='Chưa thanh toán' THEN SoTien ELSE 0 END),0) ChuaThu FROM tienphat".($rid&&!managerLike()?" WHERE MaDocGia=$rid":''))->fetch_assoc();aok(['rows'=>$rows,'totals'=>$tot]);
case 'fine_action': if(!managerLike())afail('Không có quyền.',403);$id=(int)($d['id']??0);$mode=(string)($d['mode']??'');$reason=trim((string)($d['reason']??''));$emp=currentEmployeeId();if($mode==='paid'){$s=$conn->prepare("UPDATE tienphat SET TrangThai='Đã thanh toán',NgayThanhToan=NOW(),MaNhanVienThu=NULLIF(?,0) WHERE MaTienPhat=?");$s->bind_param('ii',$emp,$id);$s->execute();}elseif($mode==='waive'){$s=$conn->prepare("UPDATE tienphat SET TrangThai='Miễn phạt',LyDoMienGiam=?,NgayThanhToan=NOW(),MaNhanVienThu=NULLIF(?,0) WHERE MaTienPhat=?");$s->bind_param('sii',$reason,$emp,$id);$s->execute();}else afail('Thao tác không hợp lệ.');audit($conn,'Xử lý tiền phạt','#'.$id,$mode);aok();

case 'receipt':
 $loan=(int)($_GET['loanId']??0);$rid=currentReaderId();$where=($rid&&!managerLike())?' AND pm.MaDocGia='.$rid:'';$s=$conn->prepare("SELECT pm.*,dg.HoTen DocGia,nv.HoTen NhanVien,GROUP_CONCAT(CONCAT(s.TenSach,' x',ct.SoLuong) SEPARATOR '||') Sach,COALESCE(SUM(ct.TienPhat),0) TienPhat FROM phieumuon pm JOIN docgia dg ON dg.MaDocGia=pm.MaDocGia LEFT JOIN nhanvien nv ON nv.MaNhanVien=pm.MaNhanVien LEFT JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon LEFT JOIN sach s ON s.MaSach=ct.MaSach WHERE pm.MaPhieuMuon=? $where GROUP BY pm.MaPhieuMuon");$s->bind_param('i',$loan);$s->execute();$r=$s->get_result()->fetch_assoc();if(!$r)afail('Không tìm thấy phiếu.',404);aok($r);

case 'recommendations':
 $rid=currentReaderId();if(!$rid)afail('Tài khoản chưa liên kết độc giả.');$s=$conn->prepare("SELECT s.MaSach,s.TenSach,s.TacGia,s.HinhAnh,s.SoLuong,t.TenTheLoai,COALESCE(pop.LuotMuon,0) LuotMuon FROM sach s LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai LEFT JOIN (SELECT MaSach,SUM(SoLuong) LuotMuon FROM chitietphieumuon GROUP BY MaSach) pop ON pop.MaSach=s.MaSach WHERE s.MaTheLoai IN (SELECT DISTINCT s2.MaTheLoai FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon JOIN sach s2 ON s2.MaSach=ct.MaSach WHERE pm.MaDocGia=?) AND s.MaSach NOT IN (SELECT ct2.MaSach FROM phieumuon pm2 JOIN chitietphieumuon ct2 ON ct2.MaPhieuMuon=pm2.MaPhieuMuon WHERE pm2.MaDocGia=?) ORDER BY LuotMuon DESC,s.MaSach DESC LIMIT 8");$s->bind_param('ii',$rid,$rid);$s->execute();aok(aall($s->get_result()));
case 'wishlist': $rid=currentReaderId();if(!$rid)afail('Chưa liên kết độc giả.');$s=$conn->prepare("SELECT y.*,s.TenSach,s.TacGia,s.SoLuong,s.HinhAnh FROM yeuthich y JOIN sach s ON s.MaSach=y.MaSach WHERE y.MaDocGia=? ORDER BY y.NgayThem DESC");$s->bind_param('i',$rid);$s->execute();aok(aall($s->get_result()));
case 'wishlist_toggle': $rid=currentReaderId();if(!$rid)afail('Chưa liên kết độc giả.');$book=(int)($d['bookId']??0);$s=$conn->prepare("SELECT MaYeuThich FROM yeuthich WHERE MaDocGia=? AND MaSach=?");$s->bind_param('ii',$rid,$book);$s->execute();if($row=$s->get_result()->fetch_assoc()){$id=(int)$row['MaYeuThich'];$conn->query("DELETE FROM yeuthich WHERE MaYeuThich=$id");$added=false;}else{$s=$conn->prepare("INSERT INTO yeuthich(MaDocGia,MaSach) VALUES(?,?)");$s->bind_param('ii',$rid,$book);$s->execute();$added=true;}aok(['added'=>$added]);

case 'queue':
 // Hết 24 giờ: trả bản giữ về trạng thái có sẵn và tự chuyển quyền giữ cho người kế tiếp.
 $expired=aall($conn->query("SELECT MaHangCho,MaSach FROM hangchodatsach WHERE TrangThai='Đang giữ' AND GiuDen IS NOT NULL AND GiuDen<NOW()"));
 foreach($expired as $ex){$qid=(int)$ex['MaHangCho'];$bid=(int)$ex['MaSach'];$conn->query("UPDATE hangchodatsach SET TrangThai='Hết hạn' WHERE MaHangCho=$qid");$conn->query("UPDATE cuonsach SET TrangThai='Có sẵn' WHERE MaSach=$bid AND TrangThai='Đang giữ chỗ' ORDER BY MaCuon LIMIT 1");$nx=$conn->query("SELECT MaHangCho,MaDocGia FROM hangchodatsach WHERE MaSach=$bid AND TrangThai='Đang chờ' ORDER BY ThuTu,NgayDat LIMIT 1")->fetch_assoc();if($nx){$nid=(int)$nx['MaHangCho'];$nr=(int)$nx['MaDocGia'];$conn->query("UPDATE hangchodatsach SET TrangThai='Đang giữ',GiuDen=DATE_ADD(NOW(),INTERVAL 24 HOUR) WHERE MaHangCho=$nid");$conn->query("UPDATE cuonsach SET TrangThai='Đang giữ chỗ' WHERE MaSach=$bid AND TrangThai='Có sẵn' ORDER BY MaCuon LIMIT 1");$ur=$conn->query("SELECT MaTaiKhoan FROM taikhoan WHERE MaDocGia=$nr LIMIT 1")->fetch_assoc();if($ur){$u=(int)$ur['MaTaiKhoan'];$tt='Đến lượt bạn nhận sách';$cc='Sách trong hàng chờ đã được giữ cho bạn trong 24 giờ.';$ins=$conn->prepare("INSERT INTO thongbao(MaTaiKhoan,MaDocGia,TieuDe,NoiDung,Loai,DuongDan) VALUES(?,?,?,?,'success','sach.php')");$ins->bind_param('iiss',$u,$nr,$tt,$cc);$ins->execute();}}}
 $rid=currentReaderId();$condition=managerLike()?'':($rid?" WHERE h.MaDocGia=$rid":" WHERE 1=0");$rows=aall($conn->query("SELECT h.*,d.HoTen,s.TenSach FROM hangchodatsach h JOIN docgia d ON d.MaDocGia=h.MaDocGia JOIN sach s ON s.MaSach=h.MaSach $condition ORDER BY h.MaSach,h.TrangThai='Đang giữ' DESC,h.ThuTu,h.NgayDat"));aok($rows);
case 'queue_join': $rid=currentReaderId();if(!$rid)afail('Chưa liên kết độc giả.');$book=(int)($d['bookId']??0);$chk=$conn->prepare("SELECT 1 FROM hangchodatsach WHERE MaDocGia=? AND MaSach=? AND TrangThai IN('Đang chờ','Đang giữ')");$chk->bind_param('ii',$rid,$book);$chk->execute();if($chk->get_result()->fetch_assoc())afail('Bạn đã ở trong hàng chờ của sách này.');$s=$conn->prepare("SELECT COALESCE(MAX(ThuTu),0)+1 n FROM hangchodatsach WHERE MaSach=? AND TrangThai='Đang chờ'");$s->bind_param('i',$book);$s->execute();$n=(int)$s->get_result()->fetch_assoc()['n'];$i=$conn->prepare("INSERT INTO hangchodatsach(MaDocGia,MaSach,ThuTu) VALUES(?,?,?)");$i->bind_param('iii',$rid,$book,$n);$i->execute();aok(['position'=>$n],'Đã vào hàng chờ.');
case 'queue_hold_next': if(!managerLike())afail('Không có quyền.',403);$book=(int)($d['bookId']??0);$conn->begin_transaction();try{$s=$conn->prepare("SELECT MaHangCho,MaDocGia FROM hangchodatsach WHERE MaSach=? AND TrangThai='Đang chờ' ORDER BY ThuTu,NgayDat LIMIT 1 FOR UPDATE");$s->bind_param('i',$book);$s->execute();$r=$s->get_result()->fetch_assoc();if(!$r)throw new Exception('Không còn người trong hàng chờ.');$id=(int)$r['MaHangCho'];$rid2=(int)$r['MaDocGia'];$conn->query("UPDATE hangchodatsach SET TrangThai='Đang giữ',GiuDen=DATE_ADD(NOW(),INTERVAL 24 HOUR) WHERE MaHangCho=$id");$conn->query("UPDATE cuonsach SET TrangThai='Đang giữ chỗ' WHERE MaSach=$book AND TrangThai='Có sẵn' ORDER BY MaCuon LIMIT 1");$uidRow=$conn->query("SELECT MaTaiKhoan FROM taikhoan WHERE MaDocGia=$rid2 LIMIT 1")->fetch_assoc();if($uidRow){$uid2=(int)$uidRow['MaTaiKhoan'];$title='Sách đã sẵn sàng';$content='Sách bạn đặt đã được giữ trong 24 giờ.';$in=$conn->prepare("INSERT INTO thongbao(MaTaiKhoan,MaDocGia,TieuDe,NoiDung,Loai,DuongDan) VALUES(?,?,?,?,'success','sach.php')");$in->bind_param('iiss',$uid2,$rid2,$title,$content);$in->execute();}$conn->commit();aok(['readerId'=>$rid2]);}catch(Throwable $e){$conn->rollback();afail($e->getMessage());}

case 'receipt_create':
 if(!managerLike())afail('Không có quyền.',403);$supplier=(int)($d['supplierId']??0);$book=(int)($d['bookId']??0);$qty=max(1,(int)($d['qty']??1));$price=max(0,(float)($d['price']??0));$note=trim((string)($d['note']??''));$emp=currentEmployeeId();if(!$book)afail('Chọn mã sách.');$total=$qty*$price;$conn->begin_transaction();try{$sp=$supplier?:null;$ep=$emp?:null;$st=$conn->prepare("INSERT INTO phieunhap(MaNCC,MaNhanVien,TongTien,GhiChu) VALUES(?,?,?,NULLIF(?,''))");$st->bind_param('iids',$sp,$ep,$total,$note);$st->execute();$receipt=$conn->insert_id;$ct=$conn->prepare("INSERT INTO chitietphieunhap(MaPhieuNhap,MaSach,SoLuong,DonGia) VALUES(?,?,?,?)");$ct->bind_param('iiid',$receipt,$book,$qty,$price);$ct->execute();$conn->query("UPDATE sach SET SoLuong=SoLuong+$qty WHERE MaSach=$book");$start=(int)$conn->query("SELECT COUNT(*) c FROM cuonsach WHERE MaSach=$book")->fetch_assoc()['c'];$ins=$conn->prepare("INSERT INTO cuonsach(MaSach,MaVach,TrangThai,NgayNhap) VALUES(?,?,'Có sẵn',CURDATE())");for($i=1;$i<=$qty;$i++){$code=sprintf('TV-S%03d-%02d',$book,$start+$i);$ins->bind_param('is',$book,$code);$ins->execute();}$lg=$conn->prepare("INSERT INTO nhatkytonkho(MaSach,Loai,SoLuong,GhiChu,MaNhanVien) VALUES(?,'Nhập',?,?,NULLIF(?,0))");$detail='Phiếu nhập #'.$receipt.' • '.number_format($price,0,',','.').'đ/cuốn';$lg->bind_param('iisi',$book,$qty,$detail,$emp);$lg->execute();$conn->commit();audit($conn,'Tạo phiếu nhập','Phiếu #'.$receipt,'Sách #'.$book.' x'.$qty);aok(['receiptId'=>$receipt,'total'=>$total]);}catch(Throwable $e){$conn->rollback();afail($e->getMessage());}

case 'book_meta_update': if(!managerLike())afail('Không có quyền.',403);$id=(int)($d['bookId']??0);$isbn=trim((string)($d['isbn']??''));$loc=trim((string)($d['location']??''));$s=$conn->prepare("UPDATE sach SET ISBN=NULLIF(?,''),ViTriKe=NULLIF(?,'') WHERE MaSach=?");$s->bind_param('ssi',$isbn,$loc,$id);$s->execute();$s=$conn->prepare("UPDATE cuonsach SET ViTriKe=NULLIF(?,'') WHERE MaSach=? AND (ViTriKe IS NULL OR ViTriKe='')");$s->bind_param('si',$loc,$id);$s->execute();audit($conn,'Cập nhật ISBN/vị trí','Sách #'.$id,$loc);aok();
case 'review_moderate': if(!in_array(currentLibraryRoleKey(),['admin','manager'],true))afail('Không có quyền.',403);$id=(int)($d['id']??0);$status=(string)($d['status']??'Ẩn');if(!in_array($status,['Hiển thị','Ẩn'],true))afail('Trạng thái không hợp lệ.');$s=$conn->prepare("UPDATE danhgia SET TrangThai=? WHERE MaDanhGia=?");$s->bind_param('si',$status,$id);$s->execute();audit($conn,'Kiểm duyệt đánh giá','#'.$id,$status);aok();

case 'inventory': if(!managerLike())afail('Không có quyền.',403);$sup=aall($conn->query("SELECT * FROM nhacungcap ORDER BY MaNCC DESC"));$receipts=aall($conn->query("SELECT p.*,n.TenNCC,nv.HoTen NhanVien FROM phieunhap p LEFT JOIN nhacungcap n ON n.MaNCC=p.MaNCC LEFT JOIN nhanvien nv ON nv.MaNhanVien=p.MaNhanVien ORDER BY p.MaPhieuNhap DESC LIMIT 30"));$logs=aall($conn->query("SELECT l.*,s.TenSach,c.MaVach,nv.HoTen NhanVien FROM nhatkytonkho l JOIN sach s ON s.MaSach=l.MaSach LEFT JOIN cuonsach c ON c.MaCuon=l.MaCuon LEFT JOIN nhanvien nv ON nv.MaNhanVien=l.MaNhanVien ORDER BY l.MaNhatKy DESC LIMIT 50"));aok(compact('sup','receipts','logs'));
case 'supplier_save': if(!managerLike())afail('Không có quyền.',403);$name=trim((string)($d['name']??''));if($name==='')afail('Tên nhà cung cấp không được trống.');$phone=trim((string)($d['phone']??''));$email=trim((string)($d['email']??''));$addr=trim((string)($d['address']??''));$s=$conn->prepare("INSERT INTO nhacungcap(TenNCC,SDT,Email,DiaChi) VALUES(?,NULLIF(?,''),NULLIF(?,''),NULLIF(?,''))");$s->bind_param('ssss',$name,$phone,$email,$addr);$s->execute();audit($conn,'Thêm nhà cung cấp',$name);aok(['id'=>$conn->insert_id]);
case 'stock_adjust': if(!managerLike())afail('Không có quyền.',403);$book=(int)($d['bookId']??0);$type=trim((string)($d['type']??''));$qty=max(1,(int)($d['qty']??1));$note=trim((string)($d['note']??''));$emp=currentEmployeeId();if(!in_array($type,['Nhập','Mất','Hỏng','Thanh lý','Kiểm kê'],true))afail('Loại điều chỉnh không hợp lệ.');$conn->begin_transaction();try{if($type==='Nhập'){$conn->query("UPDATE sach SET SoLuong=SoLuong+$qty WHERE MaSach=$book");$start=(int)$conn->query("SELECT COUNT(*) c FROM cuonsach WHERE MaSach=$book")->fetch_assoc()['c'];$ins=$conn->prepare("INSERT INTO cuonsach(MaSach,MaVach,TrangThai,NgayNhap) VALUES(?,?,'Có sẵn',CURDATE())");for($i=1;$i<=$qty;$i++){$code=sprintf('TV-S%03d-%02d',$book,$start+$i);$ins->bind_param('is',$book,$code);$ins->execute();}}else if(in_array($type,['Mất','Hỏng','Thanh lý'],true)){$status=$type;$q=$conn->query("SELECT MaCuon FROM cuonsach WHERE MaSach=$book AND TrangThai='Có sẵn' ORDER BY MaCuon LIMIT $qty");$ids=array_map(fn($r)=>(int)$r['MaCuon'],aall($q));if(count($ids)<$qty)throw new Exception('Không đủ cuốn đang có sẵn để điều chỉnh.');foreach($ids as $cid)$conn->query("UPDATE cuonsach SET TrangThai='$status' WHERE MaCuon=$cid");$conn->query("UPDATE sach SET SoLuong=GREATEST(0,SoLuong-$qty) WHERE MaSach=$book");}$s=$conn->prepare("INSERT INTO nhatkytonkho(MaSach,Loai,SoLuong,GhiChu,MaNhanVien) VALUES(?,?,?,?,NULLIF(?,0))");$s->bind_param('isisi',$book,$type,$qty,$note,$emp);$s->execute();$conn->commit();audit($conn,'Điều chỉnh tồn kho','Sách #'.$book,"$type $qty");aok();}catch(Throwable $e){$conn->rollback();afail($e->getMessage());}

case 'audit': if(!managerLike())afail('Không có quyền.',403);aok(aall($conn->query("SELECT * FROM nhatkyhoatdong ORDER BY MaNhatKy DESC LIMIT 150")));
case 'staff_profiles': if(!managerLike() && currentLibraryRoleKey()!=='employee')afail('Không có quyền.',403);$eid=currentEmployeeId();$where=currentLibraryRoleKey()==='employee'?" WHERE n.MaNhanVien=$eid":'';aok(aall($conn->query("SELECT n.*,COUNT(pc.MaPhanCong) SoCaThang FROM nhanvien n LEFT JOIN phancongca pc ON pc.MaNhanVien=n.MaNhanVien AND YEAR(pc.NgayLam)=YEAR(CURDATE()) AND MONTH(pc.NgayLam)=MONTH(CURDATE()) $where GROUP BY n.MaNhanVien ORDER BY n.MaNhanVien DESC")));
case 'shift_board':
 $eid=currentEmployeeId();$rows=aall($conn->query("SELECT c.*,x.NgayLam,COUNT(DISTINCT pc.MaPhanCong) DaPhanCong,COUNT(DISTINCT dk.MaDangKy) DangKyChoDuyet FROM calamviec c CROSS JOIN (SELECT CURDATE() NgayLam UNION SELECT DATE_ADD(CURDATE(),INTERVAL 1 DAY) UNION SELECT DATE_ADD(CURDATE(),INTERVAL 2 DAY) UNION SELECT DATE_ADD(CURDATE(),INTERVAL 3 DAY) UNION SELECT DATE_ADD(CURDATE(),INTERVAL 4 DAY) UNION SELECT DATE_ADD(CURDATE(),INTERVAL 5 DAY) UNION SELECT DATE_ADD(CURDATE(),INTERVAL 6 DAY)) x LEFT JOIN phancongca pc ON pc.MaCa=c.MaCa AND pc.NgayLam=x.NgayLam LEFT JOIN dangkyca dk ON dk.MaCa=c.MaCa AND dk.NgayLam=x.NgayLam AND dk.TrangThai='Chờ duyệt' WHERE c.TrangThai='Hoạt động' GROUP BY c.MaCa,x.NgayLam ORDER BY x.NgayLam,c.GioBatDau"));$mine=[];if($eid){$s=$conn->prepare("SELECT * FROM dangkyca WHERE MaNhanVien=? AND NgayLam>=CURDATE() ORDER BY NgayLam");$s->bind_param('i',$eid);$s->execute();$mine=aall($s->get_result());}aok(['rows'=>$rows,'mine'=>$mine]);
case 'shift_register': $eid=currentEmployeeId();if(!$eid)afail('Chỉ nhân viên mới đăng ký ca.');$shift=(int)($d['shiftId']??0);$date=(string)($d['date']??'');$overlap=$conn->prepare("SELECT 1 FROM dangkyca d JOIN calamviec c ON c.MaCa=d.MaCa JOIN calamviec n ON n.MaCa=? WHERE d.MaNhanVien=? AND d.NgayLam=? AND d.TrangThai IN('Chờ duyệt','Đã duyệt') AND c.GioBatDau<n.GioKetThuc AND c.GioKetThuc>n.GioBatDau LIMIT 1");$overlap->bind_param('iis',$shift,$eid,$date);$overlap->execute();if($overlap->get_result()->fetch_assoc())afail('Bạn đã có ca trùng thời gian.');$s=$conn->prepare("INSERT INTO dangkyca(MaNhanVien,MaCa,NgayLam) VALUES(?,?,?) ON DUPLICATE KEY UPDATE TrangThai='Chờ duyệt',NgayDangKy=NOW()");$s->bind_param('iis',$eid,$shift,$date);$s->execute();audit($conn,'Đăng ký ca','Ca #'.$shift,$date);aok();
case 'shift_requests': if(!in_array(currentLibraryRoleKey(),['manager','admin'],true))afail('Không có quyền.',403);aok(aall($conn->query("SELECT d.*,n.HoTen,c.TenCa,c.GioBatDau,c.GioKetThuc FROM dangkyca d JOIN nhanvien n ON n.MaNhanVien=d.MaNhanVien JOIN calamviec c ON c.MaCa=d.MaCa ORDER BY d.TrangThai='Chờ duyệt' DESC,d.NgayLam,d.NgayDangKy")));
case 'shift_decide': if(!in_array(currentLibraryRoleKey(),['manager','admin'],true))afail('Không có quyền.',403);$id=(int)($d['id']??0);$mode=(string)($d['mode']??'');$r=$conn->query("SELECT * FROM dangkyca WHERE MaDangKy=$id")->fetch_assoc();if(!$r)afail('Không tìm thấy đăng ký.');if($mode==='approve'){$emp=(int)$r['MaNhanVien'];$shift=(int)$r['MaCa'];$date=$r['NgayLam'];$cap=$conn->query("SELECT SoNguoiToiDa FROM calamviec WHERE MaCa=$shift")->fetch_assoc();$max=max(1,(int)($cap['SoNguoiToiDa']??4));$assigned=(int)$conn->query("SELECT COUNT(*) c FROM phancongca WHERE MaCa=$shift AND NgayLam='".$conn->real_escape_string($date)."'")->fetch_assoc()['c'];if($assigned>=$max)afail('Ca này đã đủ người.');$conn->query("UPDATE dangkyca SET TrangThai='Đã duyệt' WHERE MaDangKy=$id");$s=$conn->prepare("INSERT IGNORE INTO phancongca(MaNhanVien,MaCa,NgayLam,GhiChu) VALUES(?,?,?,'Nhân viên tự đăng ký')");$s->bind_param('iis',$emp,$shift,$date);$s->execute();}elseif($mode==='reject'){$conn->query("UPDATE dangkyca SET TrangThai='Từ chối' WHERE MaDangKy=$id");}else afail('Thao tác không hợp lệ.');audit($conn,'Duyệt đăng ký ca','#'.$id,$mode);aok();

case 'global_search':
 $q=trim((string)($_GET['q']??''));if(mb_strlen($q)<1)aok([]);$like='%'.$q.'%';$out=[];
 $s=$conn->prepare("SELECT s.MaSach id,s.TenSach title,CONCAT('Sách • ',COALESCE(s.TacGia,''),' • ',COALESCE(t.TenTheLoai,'Chưa phân loại')) subtitle,'sach.php' page,'book' kind,COALESCE(s.HinhAnh,'') image FROM sach s LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai WHERE s.TenSach LIKE ? OR s.TacGia LIKE ? OR CAST(s.MaSach AS CHAR) LIKE ? OR t.TenTheLoai LIKE ? LIMIT 8");$s->bind_param('ssss',$like,$like,$like,$like);$s->execute();$out=array_merge($out,aall($s->get_result()));
 $s=$conn->prepare("SELECT MaTheLoai id,TenTheLoai title,CONCAT('Thể loại • ',COALESCE(MoTa,'')) subtitle,'sach.php' page,'category' kind,'' image FROM theloai WHERE TenTheLoai LIKE ? OR MoTa LIKE ? LIMIT 5");$s->bind_param('ss',$like,$like);$s->execute();$out=array_merge($out,aall($s->get_result()));
 if(managerLike()){
  $s=$conn->prepare("SELECT MaDocGia id,HoTen title,CONCAT('Độc giả • ',COALESCE(SDT,'')) subtitle,'docgia.php' page,'reader' kind,'' image FROM docgia WHERE HoTen LIKE ? OR SDT LIKE ? OR Email LIKE ? LIMIT 6");$s->bind_param('sss',$like,$like,$like);$s->execute();$out=array_merge($out,aall($s->get_result()));
  $s=$conn->prepare("SELECT MaNhanVien id,HoTen title,CONCAT('Nhân viên • ',COALESCE(VaiTro,'')) subtitle,'nhanvien.php' page,'employee' kind,'' image FROM nhanvien WHERE HoTen LIKE ? OR SDT LIKE ? OR Email LIKE ? LIMIT 6");$s->bind_param('sss',$like,$like,$like);$s->execute();$out=array_merge($out,aall($s->get_result()));
  $digits=preg_replace('/\D+/','',$q);if($digits!==''){$pid=(int)$digits;$s=$conn->prepare("SELECT pm.MaPhieuMuon id,CONCAT('Phiếu mượn #',pm.MaPhieuMuon) title,CONCAT('Độc giả • ',COALESCE(d.HoTen,''),' • ',COALESCE(pm.TrangThai,'')) subtitle,'muontra.php' page,'loan' kind,'' image FROM phieumuon pm LEFT JOIN docgia d ON d.MaDocGia=pm.MaDocGia WHERE pm.MaPhieuMuon=? LIMIT 1");$s->bind_param('i',$pid);$s->execute();$out=array_merge($out,aall($s->get_result()));}
 }
 aok($out);

case 'book_detail': $id=(int)($_GET['id']??0);$s=$conn->prepare("SELECT s.*,t.TenTheLoai,COALESCE(AVG(CASE WHEN dg.TrangThai='Hiển thị' THEN dg.SoSao END),0) DiemDanhGia,COUNT(CASE WHEN dg.TrangThai='Hiển thị' THEN 1 END) SoDanhGia,COALESCE(SUM(ct.SoLuong),0) LuotMuon FROM sach s LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai LEFT JOIN danhgia dg ON dg.MaSach=s.MaSach LEFT JOIN chitietphieumuon ct ON ct.MaSach=s.MaSach WHERE s.MaSach=? GROUP BY s.MaSach");$s->bind_param('i',$id);$s->execute();$book=$s->get_result()->fetch_assoc();if(!$book)afail('Không tìm thấy sách.',404);$s=$conn->prepare("SELECT dg.*,d.HoTen FROM danhgia dg JOIN docgia d ON d.MaDocGia=dg.MaDocGia WHERE dg.MaSach=? AND dg.TrangThai='Hiển thị' ORDER BY dg.NgayDanhGia DESC LIMIT 20");$s->bind_param('i',$id);$s->execute();$reviews=aall($s->get_result());$sim=[];if(!empty($book['MaTheLoai'])){$cat=(int)$book['MaTheLoai'];$s=$conn->prepare("SELECT MaSach,TenSach,TacGia,HinhAnh FROM sach WHERE MaTheLoai=? AND MaSach<>? ORDER BY MaSach DESC LIMIT 4");$s->bind_param('ii',$cat,$id);$s->execute();$sim=aall($s->get_result());}aok(compact('book','reviews','sim'));
case 'review_save': $rid=currentReaderId();if(!$rid)afail('Chưa liên kết độc giả.');$book=(int)($d['bookId']??0);$stars=max(1,min(5,(int)($d['stars']??5)));$text=trim((string)($d['text']??''));$s=$conn->prepare("SELECT 1 FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon WHERE pm.MaDocGia=? AND ct.MaSach=? LIMIT 1");$s->bind_param('ii',$rid,$book);$s->execute();if(!$s->get_result()->fetch_assoc())afail('Chỉ độc giả từng mượn sách mới được đánh giá.');$s=$conn->prepare("INSERT INTO danhgia(MaDocGia,MaSach,SoSao,NoiDung) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE SoSao=VALUES(SoSao),NoiDung=VALUES(NoiDung),TrangThai='Hiển thị',NgayDanhGia=NOW()");$s->bind_param('iiis',$rid,$book,$stars,$text);$s->execute();aok();

case 'reader_for_you':
 $rid=currentReaderId();if(!$rid)afail('Chưa liên kết độc giả.');
 $fav=null;$s=$conn->prepare("SELECT s.MaTheLoai,t.TenTheLoai,SUM(ct.SoLuong) score FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon JOIN sach s ON s.MaSach=ct.MaSach LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai WHERE pm.MaDocGia=? AND s.MaTheLoai IS NOT NULL GROUP BY s.MaTheLoai,t.TenTheLoai ORDER BY score DESC LIMIT 1");$s->bind_param('i',$rid);$s->execute();$fav=$s->get_result()->fetch_assoc();
 $because=[];if($fav){$cat=(int)$fav['MaTheLoai'];$s=$conn->prepare("SELECT s.MaSach,s.TenSach,s.TacGia,s.HinhAnh,s.SoLuong,t.TenTheLoai,COALESCE(pop.LuotMuon,0) LuotMuon FROM sach s LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai LEFT JOIN (SELECT MaSach,SUM(SoLuong) LuotMuon FROM chitietphieumuon GROUP BY MaSach) pop ON pop.MaSach=s.MaSach WHERE s.MaTheLoai=? AND s.MaSach NOT IN (SELECT ct.MaSach FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon WHERE pm.MaDocGia=?) ORDER BY LuotMuon DESC,s.MaSach DESC LIMIT 8");$s->bind_param('ii',$cat,$rid);$s->execute();$because=aall($s->get_result());}
 $next=[];$s=$conn->prepare("SELECT s.MaSach,s.TenSach,s.TacGia,s.HinhAnh,s.SoLuong,t.TenTheLoai,COALESCE(pop.LuotMuon,0) LuotMuon FROM yeuthich y JOIN sach s ON s.MaSach=y.MaSach LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai LEFT JOIN (SELECT MaSach,SUM(SoLuong) LuotMuon FROM chitietphieumuon GROUP BY MaSach) pop ON pop.MaSach=s.MaSach WHERE y.MaDocGia=? ORDER BY s.SoLuong>0 DESC,y.NgayThem DESC LIMIT 8");$s->bind_param('i',$rid);$s->execute();$next=aall($s->get_result());
 $similar=[];if($fav){$cat=(int)$fav['MaTheLoai'];$s=$conn->prepare("SELECT s.MaSach,s.TenSach,s.TacGia,s.HinhAnh,s.SoLuong,t.TenTheLoai,SUM(ct.SoLuong) LuotMuon FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon JOIN sach s ON s.MaSach=ct.MaSach LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai WHERE pm.MaDocGia<>? AND s.MaTheLoai=? AND s.MaSach NOT IN (SELECT ct2.MaSach FROM phieumuon pm2 JOIN chitietphieumuon ct2 ON ct2.MaPhieuMuon=pm2.MaPhieuMuon WHERE pm2.MaDocGia=?) GROUP BY s.MaSach,s.TenSach,s.TacGia,s.HinhAnh,s.SoLuong,t.TenTheLoai ORDER BY LuotMuon DESC LIMIT 8");$s->bind_param('iii',$rid,$cat,$rid);$s->execute();$similar=aall($s->get_result());}
 aok(['favorite'=>$fav,'because'=>$because,'next'=>$next,'similar'=>$similar]);

case 'reader_journey':
 $rid=currentReaderId();if(!$rid)afail('Chưa liên kết độc giả.');
 $s=$conn->prepare("SELECT pm.MaPhieuMuon,pm.NgayMuon,pm.HanTra,pm.NgayTra,pm.TrangThai,GROUP_CONCAT(DISTINCT s.TenSach ORDER BY s.TenSach SEPARATOR '||') Sach,COALESCE(SUM(ct.SoLuong),0) SoCuon FROM phieumuon pm LEFT JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon LEFT JOIN sach s ON s.MaSach=ct.MaSach WHERE pm.MaDocGia=? GROUP BY pm.MaPhieuMuon ORDER BY pm.NgayMuon DESC,pm.MaPhieuMuon DESC LIMIT 40");$s->bind_param('i',$rid);$s->execute();$history=aall($s->get_result());
 $s=$conn->prepare("SELECT DATE_FORMAT(pm.NgayMuon,'%Y-%m') ym,DATE_FORMAT(pm.NgayMuon,'%m/%Y') label,COUNT(DISTINCT pm.MaPhieuMuon) LuotMuon,COALESCE(SUM(ct.SoLuong),0) SoCuon FROM phieumuon pm LEFT JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon WHERE pm.MaDocGia=? AND pm.NgayMuon>=DATE_SUB(CURDATE(),INTERVAL 11 MONTH) GROUP BY YEAR(pm.NgayMuon),MONTH(pm.NgayMuon) ORDER BY ym");$s->bind_param('i',$rid);$s->execute();$monthly=aall($s->get_result());
 $total=0;foreach($history as $h)$total+=(int)($h['SoCuon']??0);$milestones=[];foreach([1,5,10,20,50] as $m)if($total>=$m)$milestones[]=['count'=>$m,'label'=>$m===1?'Cuốn đầu tiên':('Cột mốc '.$m.' cuốn')];
 aok(['history'=>$history,'monthly'=>$monthly,'totalBooks'=>$total,'milestones'=>$milestones]);

case 'reading_profile_reader':
 $rid=(int)($_GET['readerId']??0);if(!$rid)afail('Chưa chọn độc giả.');if(!managerLike() && $rid!==currentReaderId())afail('Không có quyền.',403);
 $s=$conn->prepare("SELECT d.MaDocGia,d.HoTen,COUNT(DISTINCT pm.MaPhieuMuon) LuotMuonNam,COALESCE(SUM(CASE WHEN YEAR(pm.NgayMuon)=YEAR(CURDATE()) THEN ct.SoLuong ELSE 0 END),0) SoCuonNam,ROUND(100*SUM(CASE WHEN pm.NgayTra IS NOT NULL AND pm.NgayTra<=pm.HanTra THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN pm.NgayTra IS NOT NULL THEN 1 ELSE 0 END),0),1) TyLeDungHan FROM docgia d LEFT JOIN phieumuon pm ON pm.MaDocGia=d.MaDocGia LEFT JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon WHERE d.MaDocGia=? GROUP BY d.MaDocGia,d.HoTen");$s->bind_param('i',$rid);$s->execute();$summary=$s->get_result()->fetch_assoc();if(!$summary)afail('Không tìm thấy độc giả.',404);
 $s=$conn->prepare("SELECT COALESCE(t.TenTheLoai,'Chưa phân loại') TenTheLoai,SUM(ct.SoLuong) Tong FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon JOIN sach b ON b.MaSach=ct.MaSach LEFT JOIN theloai t ON t.MaTheLoai=b.MaTheLoai WHERE pm.MaDocGia=? GROUP BY t.MaTheLoai,t.TenTheLoai ORDER BY Tong DESC LIMIT 1");$s->bind_param('i',$rid);$s->execute();$fav=$s->get_result()->fetch_assoc();
 $s=$conn->prepare("SELECT DATE_FORMAT(pm.NgayMuon,'%m/%Y') Thang,SUM(ct.SoLuong) Tong FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon WHERE pm.MaDocGia=? GROUP BY YEAR(pm.NgayMuon),MONTH(pm.NgayMuon) ORDER BY Tong DESC LIMIT 1");$s->bind_param('i',$rid);$s->execute();$best=$s->get_result()->fetch_assoc();
 $s=$conn->prepare("SELECT COUNT(DISTINCT b.MaTheLoai) c FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon JOIN sach b ON b.MaSach=ct.MaSach WHERE pm.MaDocGia=?");$s->bind_param('i',$rid);$s->execute();$catCount=(int)$s->get_result()->fetch_assoc()['c'];$badges=[];if((int)($summary['SoCuonNam']??0)>=10)$badges[]='📚 Đọc 10+ cuốn';if((float)($summary['TyLeDungHan']??0)>=90)$badges[]='⏰ Trả sách đúng hạn';if($catCount>=5)$badges[]='🧭 Khám phá 5 thể loại';
 $s=$conn->prepare("SELECT pm.MaPhieuMuon,pm.NgayMuon,pm.HanTra,pm.NgayTra,GROUP_CONCAT(b.TenSach SEPARATOR ', ') Sach FROM phieumuon pm LEFT JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon LEFT JOIN sach b ON b.MaSach=ct.MaSach WHERE pm.MaDocGia=? GROUP BY pm.MaPhieuMuon ORDER BY pm.NgayMuon DESC LIMIT 20");$s->bind_param('i',$rid);$s->execute();$history=aall($s->get_result());aok(['summary'=>$summary,'favorite'=>$fav,'bestMonth'=>$best,'badges'=>$badges,'history'=>$history]);

case 'reading_profile': $rid=currentReaderId();if(!$rid)afail('Chưa liên kết độc giả.');$s=$conn->prepare("SELECT COUNT(DISTINCT pm.MaPhieuMuon) LuotMuonNam,COALESCE(SUM(ct.SoLuong),0) SoCuonNam,ROUND(100*SUM(CASE WHEN pm.NgayTra IS NOT NULL AND pm.NgayTra<=pm.HanTra THEN 1 ELSE 0 END)/NULLIF(SUM(CASE WHEN pm.NgayTra IS NOT NULL THEN 1 ELSE 0 END),0),1) TyLeDungHan FROM phieumuon pm LEFT JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon WHERE pm.MaDocGia=? AND YEAR(pm.NgayMuon)=YEAR(CURDATE())");$s->bind_param('i',$rid);$s->execute();$summary=$s->get_result()->fetch_assoc();$s=$conn->prepare("SELECT COALESCE(t.TenTheLoai,'Chưa phân loại') TenTheLoai,SUM(ct.SoLuong) Tong FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon JOIN sach s ON s.MaSach=ct.MaSach LEFT JOIN theloai t ON t.MaTheLoai=s.MaTheLoai WHERE pm.MaDocGia=? GROUP BY t.MaTheLoai,t.TenTheLoai ORDER BY Tong DESC LIMIT 1");$s->bind_param('i',$rid);$s->execute();$fav=$s->get_result()->fetch_assoc();$s=$conn->prepare("SELECT DATE_FORMAT(pm.NgayMuon,'%m/%Y') Thang,SUM(ct.SoLuong) Tong FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon WHERE pm.MaDocGia=? GROUP BY YEAR(pm.NgayMuon),MONTH(pm.NgayMuon) ORDER BY Tong DESC LIMIT 1");$s->bind_param('i',$rid);$s->execute();$best=$s->get_result()->fetch_assoc();$badges=[];$count=(int)($summary['SoCuonNam']??0);if($count>=10)$badges[]='📚 Đọc 10+ cuốn';if((float)($summary['TyLeDungHan']??0)>=90)$badges[]='⏰ Trả sách đúng hạn';$s=$conn->prepare("SELECT COUNT(DISTINCT s.MaTheLoai) c FROM phieumuon pm JOIN chitietphieumuon ct ON ct.MaPhieuMuon=pm.MaPhieuMuon JOIN sach s ON s.MaSach=ct.MaSach WHERE pm.MaDocGia=?");$s->bind_param('i',$rid);$s->execute();if((int)$s->get_result()->fetch_assoc()['c']>=5)$badges[]='🧭 Khám phá 5 thể loại';aok(['summary'=>$summary,'favorite'=>$fav,'bestMonth'=>$best,'badges'=>$badges]);
}
afail('Chức năng không tồn tại.',404);
